/*
	This file is generated by bima
*/

#include <gtk/gtk.h>

#include "interface.h"

int
main (int argc, char *argv[])
{

  GtkWidget *main_window;

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  main_window = create_main_window ();
  gtk_widget_show (main_window);

  gtk_main ();
  return 0;

}
