/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-module.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_MODULE(x)
#define SELF_CONST(x) BIMA_MODULE_CONST(x)
#define IS_SELF(x) BIMA_IS_MODULE(x)
#define TYPE_SELF BIMA_TYPE_MODULE
#define SELF_CLASS(x) BIMA_MODULE_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_MODULE_GET_CLASS(x)

/* self typedefs */
typedef BimaModule Self;
typedef BimaModuleClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void bima_module_init (BimaModule * o) G_GNUC_UNUSED;
static void bima_module_class_init (BimaModuleClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_ID,
	PROP_NAME,
	PROP_DESCRIPTION
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_id bima_module_get_id
#define self_set_id bima_module_set_id
#define self_get_name bima_module_get_name
#define self_set_name bima_module_set_name
#define self_get_description bima_module_get_description
#define self_set_description bima_module_set_description
#define self_write_to_xml bima_module_write_to_xml
#define self_new bima_module_new
#define self_new_with_id bima_module_new_with_id
GType
bima_module_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaModuleClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_module_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaModule),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_module_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaModule", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaModule *)g_object_new(bima_module_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaModule * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaModule *
GET_NEW_VARG (const char *first, ...)
{
	BimaModule *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaModule *)g_object_new_valist (bima_module_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Module::finalize"
	BimaModule *self G_GNUC_UNUSED = BIMA_MODULE (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 30 "module.gob"
	if(self->id) { g_free ((gpointer) self->id); self->id = NULL; }
#line 114 "bima-module.c"
#line 40 "module.gob"
	if(self->name) { g_free ((gpointer) self->name); self->name = NULL; }
#line 117 "bima-module.c"
#line 50 "module.gob"
	if(self->description) { g_free ((gpointer) self->description); self->description = NULL; }
#line 120 "bima-module.c"
#line 63 "module.gob"
	if(self->parent_id) { g_free ((gpointer) self->parent_id); self->parent_id = NULL; }
#line 123 "bima-module.c"
}
#undef __GOB_FUNCTION__

static void 
bima_module_init (BimaModule * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Module::init"
#line 29 "module.gob"
	o->id =  NULL ;
#line 133 "bima-module.c"
#line 39 "module.gob"
	o->name =  NULL ;
#line 136 "bima-module.c"
#line 49 "module.gob"
	o->description =  NULL ;
#line 139 "bima-module.c"
#line 62 "module.gob"
	o->parent_id =  NULL ;
#line 142 "bima-module.c"
}
#undef __GOB_FUNCTION__
static void 
bima_module_class_init (BimaModuleClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Module::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("id" /* name */,
		 "id" /* nick */,
		 "id of module" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_ID,
		param_spec);
	param_spec = g_param_spec_string
		("name" /* name */,
		 "name" /* nick */,
		 "name of module" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_NAME,
		param_spec);
	param_spec = g_param_spec_string
		("description" /* name */,
		 "description" /* nick */,
		 "description of module" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DESCRIPTION,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Module::set_property"
{
	BimaModule *self G_GNUC_UNUSED;

	self = BIMA_MODULE (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 31 "module.gob"
{ char *old = self->id; self->id = g_value_dup_string (VAL); g_free (old); }
#line 206 "bima-module.c"
		}
		break;
	case PROP_NAME:
		{
#line 41 "module.gob"
{ char *old = self->name; self->name = g_value_dup_string (VAL); g_free (old); }
#line 213 "bima-module.c"
		}
		break;
	case PROP_DESCRIPTION:
		{
#line 51 "module.gob"
{ char *old = self->description; self->description = g_value_dup_string (VAL); g_free (old); }
#line 220 "bima-module.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Module::get_property"
{
	BimaModule *self G_GNUC_UNUSED;

	self = BIMA_MODULE (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 31 "module.gob"
g_value_set_string (VAL, self->id);
#line 251 "bima-module.c"
		}
		break;
	case PROP_NAME:
		{
#line 41 "module.gob"
g_value_set_string (VAL, self->name);
#line 258 "bima-module.c"
		}
		break;
	case PROP_DESCRIPTION:
		{
#line 51 "module.gob"
g_value_set_string (VAL, self->description);
#line 265 "bima-module.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 31 "module.gob"
gchar * 
bima_module_get_id (BimaModule * self)
#line 285 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::get_id"
{
#line 31 "module.gob"
		gchar* val; g_object_get (G_OBJECT (self), "id", &val, NULL); return val;
}}
#line 292 "bima-module.c"
#undef __GOB_FUNCTION__

#line 31 "module.gob"
void 
bima_module_set_id (BimaModule * self, gchar * val)
#line 298 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::set_id"
{
#line 31 "module.gob"
		g_object_set (G_OBJECT (self), "id", val, NULL);
}}
#line 305 "bima-module.c"
#undef __GOB_FUNCTION__

#line 41 "module.gob"
gchar * 
bima_module_get_name (BimaModule * self)
#line 311 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::get_name"
{
#line 41 "module.gob"
		gchar* val; g_object_get (G_OBJECT (self), "name", &val, NULL); return val;
}}
#line 318 "bima-module.c"
#undef __GOB_FUNCTION__

#line 41 "module.gob"
void 
bima_module_set_name (BimaModule * self, gchar * val)
#line 324 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::set_name"
{
#line 41 "module.gob"
		g_object_set (G_OBJECT (self), "name", val, NULL);
}}
#line 331 "bima-module.c"
#undef __GOB_FUNCTION__

#line 51 "module.gob"
gchar * 
bima_module_get_description (BimaModule * self)
#line 337 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::get_description"
{
#line 51 "module.gob"
		gchar* val; g_object_get (G_OBJECT (self), "description", &val, NULL); return val;
}}
#line 344 "bima-module.c"
#undef __GOB_FUNCTION__

#line 51 "module.gob"
void 
bima_module_set_description (BimaModule * self, gchar * val)
#line 350 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::set_description"
{
#line 51 "module.gob"
		g_object_set (G_OBJECT (self), "description", val, NULL);
}}
#line 357 "bima-module.c"
#undef __GOB_FUNCTION__

#line 65 "module.gob"
void 
bima_module_write_to_xml (BimaModule * self, FILE * ofile)
#line 363 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::write_to_xml"
#line 65 "module.gob"
	g_return_if_fail (self != NULL);
#line 65 "module.gob"
	g_return_if_fail (BIMA_IS_MODULE (self));
#line 370 "bima-module.c"
{
#line 67 "module.gob"
	
		if (self->parent_id)
			fprintf(ofile, "\t<Module id=\"%s\" name=\"%s\"  parent_id=\"%s\">\n", \ 
					self->id, self->name, self->parent_id  );
		else
			fprintf(ofile, "\t<Module id=\"%s\" name=\"%s\" >\n", \ 
					self->id, self->name);
		
		if (self->description)
			fprintf(ofile, "\t\t<Description>%s</Description>", self->description);

		fprintf(ofile, "\t</Module>\n");
	}}
#line 386 "bima-module.c"
#undef __GOB_FUNCTION__

#line 82 "module.gob"
BimaModule * 
bima_module_new (void)
#line 392 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::new"
{
#line 84 "module.gob"
	
		return GET_NEW;
	}}
#line 400 "bima-module.c"
#undef __GOB_FUNCTION__

#line 88 "module.gob"
BimaModule * 
bima_module_new_with_id (gchar * id, gchar * parent_id)
#line 406 "bima-module.c"
{
#define __GOB_FUNCTION__ "Bima:Module::new_with_id"
{
#line 90 "module.gob"
	
		BimaModule *module = bima_module_new();
		if (!module)
			return NULL;

		module->id = id;	
		if (parent_id != NULL)	
			module->parent_id = g_strdup(parent_id); 
		return module;
	}}
#line 421 "bima-module.c"
#undef __GOB_FUNCTION__
