/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-template.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_TEMPLATE(x)
#define SELF_CONST(x) BIMA_TEMPLATE_CONST(x)
#define IS_SELF(x) BIMA_IS_TEMPLATE(x)
#define TYPE_SELF BIMA_TYPE_TEMPLATE
#define SELF_CLASS(x) BIMA_TEMPLATE_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_TEMPLATE_GET_CLASS(x)

/* self typedefs */
typedef BimaTemplate Self;
typedef BimaTemplateClass SelfClass;

/* here are local prototypes */
static void bima_template_init (BimaTemplate * o) G_GNUC_UNUSED;
static void bima_template_class_init (BimaTemplateClass * c) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_add_tentity bima_template_add_tentity
#define self_add_tform bima_template_add_tform
#define self_add_treport bima_template_add_treport
#define self_add_taddition bima_template_add_taddition
#define self_load_plugin bima_template_load_plugin
#define self_load_from_file bima_template_load_from_file
#define self_new bima_template_new
GType
bima_template_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaTemplateClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_template_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaTemplate),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_template_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaTemplate", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaTemplate *)g_object_new(bima_template_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaTemplate * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaTemplate *
GET_NEW_VARG (const char *first, ...)
{
	BimaTemplate *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaTemplate *)g_object_new_valist (bima_template_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Template::finalize"
	BimaTemplate *self G_GNUC_UNUSED = BIMA_TEMPLATE (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 47 "template.gob"
	if(self->file_name) { g_free ((gpointer) self->file_name); self->file_name = NULL; }
#line 103 "bima-template.c"
#line 50 "template.gob"
	if(self->directory) { g_free ((gpointer) self->directory); self->directory = NULL; }
#line 106 "bima-template.c"
#line 53 "template.gob"
	if(self->app_type) { g_free ((gpointer) self->app_type); self->app_type = NULL; }
#line 109 "bima-template.c"
#line 56 "template.gob"
	if(self->author) { g_free ((gpointer) self->author); self->author = NULL; }
#line 112 "bima-template.c"
#line 59 "template.gob"
	if(self->description) { g_free ((gpointer) self->description); self->description = NULL; }
#line 115 "bima-template.c"
#line 62 "template.gob"
	if(self->plugin_file) { g_free ((gpointer) self->plugin_file); self->plugin_file = NULL; }
#line 118 "bima-template.c"
#define plugin (self->plugin)
#define VAR plugin
	{
#line 65 "template.gob"
	
			if (plugin) 
				g_object_unref((GObject *) plugin); 
		}
#line 127 "bima-template.c"
	memset(&plugin, 0, sizeof(plugin));
#undef VAR
#undef plugin
#define module (self->module)
#define VAR module
	{
#line 71 "template.gob"
	
			if (module) 
				g_module_close(module); 
		}
#line 139 "bima-template.c"
	memset(&module, 0, sizeof(module));
#undef VAR
#undef module
#define tentities (self->tentities)
#define VAR tentities
	{
#line 77 "template.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 154 "bima-template.c"
	memset(&tentities, 0, sizeof(tentities));
#undef VAR
#undef tentities
#define tforms (self->tforms)
#define VAR tforms
	{
#line 92 "template.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 169 "bima-template.c"
	memset(&tforms, 0, sizeof(tforms));
#undef VAR
#undef tforms
#define treports (self->treports)
#define VAR treports
	{
#line 107 "template.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 184 "bima-template.c"
	memset(&treports, 0, sizeof(treports));
#undef VAR
#undef treports
#define tadditions (self->tadditions)
#define VAR tadditions
	{
#line 122 "template.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 199 "bima-template.c"
	memset(&tadditions, 0, sizeof(tadditions));
#undef VAR
#undef tadditions
}
#undef __GOB_FUNCTION__

static void 
bima_template_init (BimaTemplate * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Template::init"
#line 24 "template.gob"
	o->file_name = NULL;
#line 212 "bima-template.c"
#line 24 "template.gob"
	o->directory = NULL;
#line 215 "bima-template.c"
#line 24 "template.gob"
	o->app_type = NULL;
#line 218 "bima-template.c"
#line 24 "template.gob"
	o->author = NULL;
#line 221 "bima-template.c"
#line 24 "template.gob"
	o->description = NULL;
#line 224 "bima-template.c"
#line 24 "template.gob"
	o->plugin_file = NULL;
#line 227 "bima-template.c"
#line 24 "template.gob"
	o->plugin = NULL;
#line 230 "bima-template.c"
#line 65 "template.gob"
	o->module = NULL;
#line 233 "bima-template.c"
#line 71 "template.gob"
	o->tentities = NULL;
#line 236 "bima-template.c"
#line 87 "template.gob"
	o->tforms = NULL;
#line 239 "bima-template.c"
#line 102 "template.gob"
	o->treports = NULL;
#line 242 "bima-template.c"
#line 117 "template.gob"
	o->tadditions = NULL;
#line 245 "bima-template.c"
}
#undef __GOB_FUNCTION__
static void 
bima_template_class_init (BimaTemplateClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Template::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__



#line 85 "template.gob"
void 
bima_template_add_tentity (BimaTemplate * self, BimaTemplateForm * tentity)
#line 265 "bima-template.c"
{
#define __GOB_FUNCTION__ "Bima:Template::add_tentity"
#line 85 "template.gob"
	g_return_if_fail (self != NULL);
#line 85 "template.gob"
	g_return_if_fail (BIMA_IS_TEMPLATE (self));
#line 272 "bima-template.c"
{
#line 87 "template.gob"
	
		self->tentities = g_list_append(self->tentities, (gpointer) tentity);
	}}
#line 278 "bima-template.c"
#undef __GOB_FUNCTION__

#line 100 "template.gob"
void 
bima_template_add_tform (BimaTemplate * self, BimaTemplateForm * tform)
#line 284 "bima-template.c"
{
#define __GOB_FUNCTION__ "Bima:Template::add_tform"
#line 100 "template.gob"
	g_return_if_fail (self != NULL);
#line 100 "template.gob"
	g_return_if_fail (BIMA_IS_TEMPLATE (self));
#line 291 "bima-template.c"
{
#line 102 "template.gob"
	
		self->tforms = g_list_append(self->tforms, (gpointer) tform);
	}}
#line 297 "bima-template.c"
#undef __GOB_FUNCTION__

#line 115 "template.gob"
void 
bima_template_add_treport (BimaTemplate * self, BimaTemplateForm * treport)
#line 303 "bima-template.c"
{
#define __GOB_FUNCTION__ "Bima:Template::add_treport"
#line 115 "template.gob"
	g_return_if_fail (self != NULL);
#line 115 "template.gob"
	g_return_if_fail (BIMA_IS_TEMPLATE (self));
#line 310 "bima-template.c"
{
#line 117 "template.gob"
	
		self->treports = g_list_append(self->treports, (gpointer) treport);
	}}
#line 316 "bima-template.c"
#undef __GOB_FUNCTION__

#line 130 "template.gob"
void 
bima_template_add_taddition (BimaTemplate * self, BimaTemplateForm * taddition)
#line 322 "bima-template.c"
{
#define __GOB_FUNCTION__ "Bima:Template::add_taddition"
#line 130 "template.gob"
	g_return_if_fail (self != NULL);
#line 130 "template.gob"
	g_return_if_fail (BIMA_IS_TEMPLATE (self));
#line 329 "bima-template.c"
{
#line 132 "template.gob"
	
		self->tadditions = g_list_append(self->tadditions, (gpointer) taddition);
	}}
#line 335 "bima-template.c"
#undef __GOB_FUNCTION__

#line 136 "template.gob"
gboolean 
bima_template_load_plugin (BimaTemplate * self)
#line 341 "bima-template.c"
{
#define __GOB_FUNCTION__ "Bima:Template::load_plugin"
#line 136 "template.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 136 "template.gob"
	g_return_val_if_fail (BIMA_IS_TEMPLATE (self), (gboolean )0);
#line 348 "bima-template.c"
{
#line 137 "template.gob"
	
		g_printf("try to load %s\n",g_strconcat(PACKAGE_PLUGIN_DIR,"/", self->plugin_file,NULL));
		GetPluginType get_plugin_type;
		
		self->module = g_module_open(g_strconcat(PACKAGE_PLUGIN_DIR,"/", self->plugin_file,NULL), G_MODULE_BIND_LAZY);
		if (self->module) {
			g_printf("module loaded \n");
			if (!g_module_symbol(self->module, "get_plugin_type", (void *)&get_plugin_type)) {
				g_warning("can't find get_plugin_type symbol in module");
				return FALSE;
			}
			self->plugin = g_object_new(get_plugin_type(),NULL);
			
			if (!self->plugin)
				return FALSE;
				
		} else {
			g_warning("can't load module");
			g_warning(g_module_error());							
			return FALSE;
		}
		return TRUE;
	}}
#line 373 "bima-template.c"
#undef __GOB_FUNCTION__

#line 160 "template.gob"
void 
bima_template_load_from_file (BimaTemplate * self, gchar * file_name)
#line 379 "bima-template.c"
{
#define __GOB_FUNCTION__ "Bima:Template::load_from_file"
#line 160 "template.gob"
	g_return_if_fail (self != NULL);
#line 160 "template.gob"
	g_return_if_fail (BIMA_IS_TEMPLATE (self));
#line 386 "bima-template.c"
{
#line 162 "template.gob"
	
		xmlDocPtr xml_doc;
		xmlNodePtr xml_node, xml_root_node, xml_node2;
		BimaTemplateForm *tform ;
		
		self->file_name = g_strdup(file_name);
		
		self->tforms = NULL;
		self->treports = NULL;
		xml_doc = xmlParseFile(file_name);
		if (xml_doc)  {
			xml_root_node = xmlDocGetRootElement(xml_doc);
			if (!xmlStrcmp(xml_root_node->name, (const xmlChar *) "BimaTemplate")) {
				self->directory = g_strconcat(get_dir_name(file_name),"/",xmlGetProp(xml_root_node,"dir"),NULL);
				self->app_type = xmlGetProp(xml_root_node,"app_type");
				self->author = xmlGetProp(xml_root_node,"author");			
				self->plugin_file = xmlGetProp(xml_root_node,"plugin");
				
				//printf("%s",template_profile->dir );
				xml_node = xml_root_node->children;
				while (xml_node != NULL) {
					if (!xmlStrcmp(xml_node->name, (const xmlChar *) "Forms")) {
						xml_node2 = xml_node->children;
						while (xml_node2 ) {
							if (xmlGetProp(xml_node2,"id")) {
								tform = bima_template_form_new();
								bima_template_form_load_from_xml(tform,xml_node2);
								bima_template_add_tform(self, tform);
							}
							xml_node2=xml_node2->next;
						}
					} 
					else if (!xmlStrcmp(xml_node->name, (const xmlChar *) "Reports")) {
						xml_node2 = xml_node->children;
						while (xml_node2 ) {
							if (xmlGetProp(xml_node2,"id")) {
								tform = bima_template_form_new();
								
								bima_template_form_load_from_xml(tform,xml_node2);
								//g_printf(" report id %s\n", tform->id);
								bima_template_add_treport(self, tform);
							}
							xml_node2=xml_node2->next;
						}
					}
					else if (!xmlStrcmp(xml_node->name, (const xmlChar *) "Entity")) {
						//xml_node2 = xml_node->children;
						//while (xml_node2 ) {
							if (xmlGetProp(xml_node,"name")) {
								tform = bima_template_form_new();
								bima_template_form_load_from_xml(tform,xml_node);
								bima_template_add_tentity(self, tform);
							}
						//	xml_node2=xml_node2->next;
						//}
					}					
					else if (!xmlStrcmp(xml_node->name,(const xmlChar *) "Additions")) {
						xml_node2 = xml_node->children;
						while (xml_node2 ) {
							if (xmlGetProp(xml_node2,"name")) {
								tform = bima_template_form_new();
								bima_template_form_load_from_xml(tform,xml_node2);
								bima_template_add_taddition(self, tform);
							}
							xml_node2=xml_node2->next;
						}
					}
					xml_node = xml_node->next;
				}
			}
			xmlFreeDoc(xml_doc);
		}
		bima_template_load_plugin(self);
	}}
#line 463 "bima-template.c"
#undef __GOB_FUNCTION__

#line 237 "template.gob"
BimaTemplate * 
bima_template_new (void)
#line 469 "bima-template.c"
{
#define __GOB_FUNCTION__ "Bima:Template::new"
{
#line 239 "template.gob"
	
		return GET_NEW;
	}}
#line 477 "bima-template.c"
#undef __GOB_FUNCTION__
