/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-property.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_PROPERTY(x)
#define SELF_CONST(x) BIMA_PROPERTY_CONST(x)
#define IS_SELF(x) BIMA_IS_PROPERTY(x)
#define TYPE_SELF BIMA_TYPE_PROPERTY
#define SELF_CLASS(x) BIMA_PROPERTY_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_PROPERTY_GET_CLASS(x)

/* self typedefs */
typedef BimaProperty Self;
typedef BimaPropertyClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void bima_property_init (BimaProperty * o) G_GNUC_UNUSED;
static void bima_property_class_init (BimaPropertyClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_NAME
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_name bima_property_get_name
#define self_set_name bima_property_set_name
#define self_vinit bima_property_vinit
#define self_vset bima_property_vset
#define self_copy bima_property_copy
#define self_pget_valist bima_property_pget_valist
#define self_v_get bima_property_v_get
#define self_pset_valist bima_property_pset_valist
#define self_v_set bima_property_v_set
#define self_load_widget bima_property_load_widget
#define self_new bima_property_new
GType
bima_property_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaPropertyClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_property_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaProperty),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_property_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaProperty", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaProperty *)g_object_new(bima_property_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaProperty * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaProperty *
GET_NEW_VARG (const char *first, ...)
{
	BimaProperty *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaProperty *)g_object_new_valist (bima_property_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Property::finalize"
	BimaProperty *self G_GNUC_UNUSED = BIMA_PROPERTY (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 33 "property.gob"
	if(self->name) { g_free ((gpointer) self->name); self->name = NULL; }
#line 114 "bima-property.c"
#line 43 "property.gob"
	if(self->type) { g_free ((gpointer) self->type); self->type = NULL; }
#line 117 "bima-property.c"
#line 46 "property.gob"
	if(self->title) { g_free ((gpointer) self->title); self->title = NULL; }
#line 120 "bima-property.c"
#define value (self->value)
#define VAR value
	{
#line 49 "property.gob"
	
			g_value_unset(&VAR);		
		}
#line 128 "bima-property.c"
	memset(&value, 0, sizeof(value));
#undef VAR
#undef value
}
#undef __GOB_FUNCTION__

static void 
bima_property_init (BimaProperty * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Property::init"
#line 32 "property.gob"
	o->name =  NULL ;
#line 141 "bima-property.c"
#line 42 "property.gob"
	o->type =  NULL ;
#line 144 "bima-property.c"
#line 45 "property.gob"
	o->title =  NULL ;
#line 147 "bima-property.c"
}
#undef __GOB_FUNCTION__
static void 
bima_property_class_init (BimaPropertyClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Property::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("name" /* name */,
		 "name" /* nick */,
		 "name of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_NAME,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Property::set_property"
{
	BimaProperty *self G_GNUC_UNUSED;

	self = BIMA_PROPERTY (object);

	switch (property_id) {
	case PROP_NAME:
		{
#line 34 "property.gob"
{ char *old = self->name; self->name = g_value_dup_string (VAL); g_free (old); }
#line 193 "bima-property.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Property::get_property"
{
	BimaProperty *self G_GNUC_UNUSED;

	self = BIMA_PROPERTY (object);

	switch (property_id) {
	case PROP_NAME:
		{
#line 34 "property.gob"
g_value_set_string (VAL, self->name);
#line 224 "bima-property.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 34 "property.gob"
gchar * 
bima_property_get_name (BimaProperty * self)
#line 244 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::get_name"
{
#line 34 "property.gob"
		gchar* val; g_object_get (G_OBJECT (self), "name", &val, NULL); return val;
}}
#line 251 "bima-property.c"
#undef __GOB_FUNCTION__

#line 34 "property.gob"
void 
bima_property_set_name (BimaProperty * self, gchar * val)
#line 257 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::set_name"
{
#line 34 "property.gob"
		g_object_set (G_OBJECT (self), "name", val, NULL);
}}
#line 264 "bima-property.c"
#undef __GOB_FUNCTION__

#line 53 "property.gob"
void 
bima_property_vinit (BimaProperty * self, gchar * type)
#line 270 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::vinit"
#line 53 "property.gob"
	g_return_if_fail (self != NULL);
#line 53 "property.gob"
	g_return_if_fail (BIMA_IS_PROPERTY (self));
#line 277 "bima-property.c"
{
#line 54 "property.gob"
	
		self->type = g_strdup(type);
		if (!g_ascii_strcasecmp(type ,"string")) {
			g_value_init(&(self->value), G_TYPE_STRING);
		} else if (!g_ascii_strcasecmp(type ,"int")) {
			g_value_init(&(self->value), G_TYPE_INT);
		}
		return;	
	}}
#line 289 "bima-property.c"
#undef __GOB_FUNCTION__

#line 64 "property.gob"
void 
bima_property_vset (BimaProperty * self, GTypeCValue * value)
#line 295 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::vset"
#line 64 "property.gob"
	g_return_if_fail (self != NULL);
#line 64 "property.gob"
	g_return_if_fail (BIMA_IS_PROPERTY (self));
#line 302 "bima-property.c"
{
#line 65 "property.gob"
	
		if (!g_ascii_strcasecmp(self->type ,"string")) {
			g_value_set_string(&(self->value), g_strdup(value));
		} else if (!g_ascii_strcasecmp(self->type ,"int")) {
			g_value_set_int(&(self->value), value);
		}
	}}
#line 312 "bima-property.c"
#undef __GOB_FUNCTION__

#line 90 "property.gob"
BimaProperty * 
bima_property_copy (BimaProperty * self)
#line 318 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::copy"
#line 90 "property.gob"
	g_return_val_if_fail (self != NULL, (BimaProperty * )0);
#line 90 "property.gob"
	g_return_val_if_fail (BIMA_IS_PROPERTY (self), (BimaProperty * )0);
#line 325 "bima-property.c"
{
#line 92 "property.gob"
	
		BimaProperty *prop;
		
		prop = GET_NEW;
		prop->name = g_strdup(self->name);
		prop->title = g_strdup(self->title);
		bima_property_vinit(prop, self->type);						
		return prop ;
	
	}}
#line 338 "bima-property.c"
#undef __GOB_FUNCTION__

#line 103 "property.gob"
void 
bima_property_pget_valist (GList * list, gchar * first_prop, va_list var_args)
#line 344 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::pget_valist"
{
#line 105 "property.gob"
	
		const gchar *prop_name;
		
		prop_name = first_prop;
		while (prop_name) {
			GValue value = {0,};
			BimaProperty *property;
			gchar *error;
			property = (BimaProperty *) bima_get_object_by_prop(list , "name", prop_name);
			if (property == NULL)
				break;

/*
			if (!g_ascii_strcasecmp(property->type ,"string")) {
				g_value_init(&value, G_TYPE_STRING);
			} else if (!g_ascii_strcasecmp(property->type ,"int")) {
				g_value_init(&value, G_TYPE_INT);
			}
*/
			G_VALUE_LCOPY(&(property->value), var_args, 0, &error);			 
			prop_name = va_arg(var_args, gchar *);
		}
	}}
#line 372 "bima-property.c"
#undef __GOB_FUNCTION__

#line 129 "property.gob"
void 
bima_property_v_get (GList * list, const gchar * first_prop, ...)
#line 378 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::v_get"
{
#line 131 "property.gob"
	
		va_list var_args;
		va_start(var_args,first_prop);
		bima_property_pget_valist(list,first_prop, var_args);
		va_end(var_args);
	}}
#line 389 "bima-property.c"
#undef __GOB_FUNCTION__

#line 138 "property.gob"
void 
bima_property_pset_valist (GList * list, gchar * first_prop, va_list var_args)
#line 395 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::pset_valist"
{
#line 140 "property.gob"
	
		const gchar *prop_name;
		
		prop_name = first_prop;
		while (prop_name) {
			GValue value = {0,};
			BimaProperty *property;
			gchar *error;
			property = (BimaProperty *) bima_get_object_by_prop(list , "name", prop_name);
			if (property == NULL)
				break;
/*
			if (!g_ascii_strcasecmp(property->type ,"string")) {
				g_value_init(&value, G_TYPE_STRING);
			} else if (!g_ascii_strcasecmp(property->type ,"int")) {
				g_value_init(&value, G_TYPE_INT);
			}
*/
			G_VALUE_COLLECT (&(property->value), var_args, 0, &error);
			prop_name = va_arg(var_args, gchar *);
		}
	}}
#line 422 "bima-property.c"
#undef __GOB_FUNCTION__

#line 163 "property.gob"
void 
bima_property_v_set (GList * list, const gchar * first_prop, ...)
#line 428 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::v_set"
{
#line 165 "property.gob"
	
		va_list var_args;
		va_start(var_args,first_prop);
		bima_property_pset_valist(list,first_prop, var_args);
		va_end(var_args);
	}}
#line 439 "bima-property.c"
#undef __GOB_FUNCTION__

#line 172 "property.gob"
void 
bima_property_load_widget (BimaProperty * self)
#line 445 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::load_widget"
#line 172 "property.gob"
	g_return_if_fail (self != NULL);
#line 172 "property.gob"
	g_return_if_fail (BIMA_IS_PROPERTY (self));
#line 452 "bima-property.c"
{
#line 174 "property.gob"
	
		if (!g_ascii_strcasecmp(self->type ,"string")) {
			bima_property_add_entry( self->name, self->title, NULL,g_value_get_string(&(self->value)));
		} else if (!g_ascii_strcasecmp(self->type ,"int")) {
			bima_property_add_number( self->name, self->title, NULL,g_value_get_int(&(self->value)),0,255,1,10);
		}
	}}
#line 462 "bima-property.c"
#undef __GOB_FUNCTION__

#line 182 "property.gob"
BimaProperty * 
bima_property_new (gchar * name, gchar * title, gchar * type)
#line 468 "bima-property.c"
{
#define __GOB_FUNCTION__ "Bima:Property::new"
{
#line 184 "property.gob"
	
		BimaProperty *prop;
		
		prop = GET_NEW;
		prop->name = g_strdup(name);
		prop->title = g_strdup(title);
		bima_property_vinit(prop, type);						
		return prop ;
	}}
#line 482 "bima-property.c"
#undef __GOB_FUNCTION__
