/* Generated by GOB (v2.0.13)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <libxml/parser.h>
#include <libxml/tree.h>

#include "bima-relation.h"
#include "bima-property.h"

#ifndef __BIMA_TEMPLATE_FORM_H__
#define __BIMA_TEMPLATE_FORM_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define BIMA_TYPE_TEMPLATE_FORM	(bima_template_form_get_type())
#define BIMA_TEMPLATE_FORM(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_template_form_get_type(), BimaTemplateForm)
#define BIMA_TEMPLATE_FORM_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_template_form_get_type(), BimaTemplateForm const)
#define BIMA_TEMPLATE_FORM_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), bima_template_form_get_type(), BimaTemplateFormClass)
#define BIMA_IS_TEMPLATE_FORM(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), bima_template_form_get_type ())

#define BIMA_TEMPLATE_FORM_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), bima_template_form_get_type(), BimaTemplateFormClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BIMA_TEMPLATE_FORM__
#define __TYPEDEF_BIMA_TEMPLATE_FORM__
typedef struct _BimaTemplateForm BimaTemplateForm;
#endif
struct _BimaTemplateForm {
	GObject __parent__;
	/*< public >*/
	gchar * id;
	gchar * name;
	gchar * prefix;
	gchar * suffix;
	gchar * file_format;
	gchar * image_file;
	BimaRelationType relation_type;
	GList * template_file;
	GList * properties;
};

/*
 * Class definition
 */
typedef struct _BimaTemplateFormClass BimaTemplateFormClass;
struct _BimaTemplateFormClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	bima_template_form_get_type	(void);
gchar * 	bima_template_form_get_id	(BimaTemplateForm * self);
void 	bima_template_form_set_id	(BimaTemplateForm * self,
					gchar * val);
void 	bima_template_form_load_from_xml	(BimaTemplateForm * self,
					xmlNodePtr xml_node);
BimaTemplateForm * 	bima_template_form_new	(void);

/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define BIMA_TEMPLATE_FORM_PROP_ID(arg)    	"id", __extension__ ({gchar *z = (arg); z;})
#define BIMA_TEMPLATE_FORM_GET_PROP_ID(arg)	"id", __extension__ ({gchar **z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define BIMA_TEMPLATE_FORM_PROP_ID(arg)    	"id",(gchar *)(arg)
#define BIMA_TEMPLATE_FORM_GET_PROP_ID(arg)	"id",(gchar **)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
