/* Generated by GOB (v2.0.13)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include "bima-attribute.h"

#ifndef __BIMA_QUERY_FIELD_H__
#define __BIMA_QUERY_FIELD_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define BIMA_TYPE_QUERY_FIELD	(bima_query_field_get_type())
#define BIMA_QUERY_FIELD(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_query_field_get_type(), BimaQueryField)
#define BIMA_QUERY_FIELD_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_query_field_get_type(), BimaQueryField const)
#define BIMA_QUERY_FIELD_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), bima_query_field_get_type(), BimaQueryFieldClass)
#define BIMA_IS_QUERY_FIELD(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), bima_query_field_get_type ())

#define BIMA_QUERY_FIELD_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), bima_query_field_get_type(), BimaQueryFieldClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BIMA_QUERY_FIELD__
#define __TYPEDEF_BIMA_QUERY_FIELD__
typedef struct _BimaQueryField BimaQueryField;
#endif
struct _BimaQueryField {
	GObject __parent__;
	/*< public >*/
	gchar * table;
	gchar * field;
	gchar * alias;
	gint sort_type;
	gint opr_type;
	BimaQueryField * left_field;
	BimaQueryField * right_field;
	BimaAttribute * attribute;
};

/*
 * Class definition
 */
typedef struct _BimaQueryFieldClass BimaQueryFieldClass;
struct _BimaQueryFieldClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	bima_query_field_get_type	(void);
gchar * 	bima_query_field_get_str	(BimaQueryField * self);
BimaQueryField * 	bima_query_field_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
