/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-connection.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_CONNECTION(x)
#define SELF_CONST(x) BIMA_CONNECTION_CONST(x)
#define IS_SELF(x) BIMA_IS_CONNECTION(x)
#define TYPE_SELF BIMA_TYPE_CONNECTION
#define SELF_CLASS(x) BIMA_CONNECTION_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_CONNECTION_GET_CLASS(x)

/* self typedefs */
typedef BimaConnection Self;
typedef BimaConnectionClass SelfClass;

/* here are local prototypes */
static void bima_connection_init (BimaConnection * o) G_GNUC_UNUSED;
static void bima_connection_class_init (BimaConnectionClass * c) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_new bima_connection_new
GType
bima_connection_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaConnectionClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_connection_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaConnection),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_connection_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaConnection", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaConnection *)g_object_new(bima_connection_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaConnection * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaConnection *
GET_NEW_VARG (const char *first, ...)
{
	BimaConnection *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaConnection *)g_object_new_valist (bima_connection_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Connection::finalize"
	BimaConnection *self G_GNUC_UNUSED = BIMA_CONNECTION (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 10 "connection.gob"
	if(self->entity_id) { g_free ((gpointer) self->entity_id); self->entity_id = NULL; }
#line 97 "bima-connection.c"
#define entity (self->entity)
#define VAR entity
	{
#line 14 "connection.gob"
	entity = NULL;}
#line 103 "bima-connection.c"
	memset(&entity, 0, sizeof(entity));
#undef VAR
#undef entity
}
#undef __GOB_FUNCTION__

static void 
bima_connection_init (BimaConnection * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Connection::init"
#line 3 "connection.gob"
	o->is_total = FALSE;
#line 116 "bima-connection.c"
#line 3 "connection.gob"
	o->entity_id = NULL;
#line 119 "bima-connection.c"
#line 3 "connection.gob"
	o->connection = 0;
#line 122 "bima-connection.c"
#line 3 "connection.gob"
	o->entity = NULL;
#line 125 "bima-connection.c"
}
#undef __GOB_FUNCTION__
static void 
bima_connection_class_init (BimaConnectionClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Connection::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__



#line 16 "connection.gob"
BimaConnection * 
bima_connection_new (void)
#line 145 "bima-connection.c"
{
#define __GOB_FUNCTION__ "Bima:Connection::new"
{
#line 18 "connection.gob"
	
		return GET_NEW;
	}}
#line 153 "bima-connection.c"
#undef __GOB_FUNCTION__
