/* Generated by GOB (v2.0.13)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <stdio.h>

#ifndef __BIMA_MODULE_H__
#define __BIMA_MODULE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define BIMA_TYPE_MODULE	(bima_module_get_type())
#define BIMA_MODULE(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_module_get_type(), BimaModule)
#define BIMA_MODULE_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_module_get_type(), BimaModule const)
#define BIMA_MODULE_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), bima_module_get_type(), BimaModuleClass)
#define BIMA_IS_MODULE(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), bima_module_get_type ())

#define BIMA_MODULE_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), bima_module_get_type(), BimaModuleClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BIMA_MODULE__
#define __TYPEDEF_BIMA_MODULE__
typedef struct _BimaModule BimaModule;
#endif
struct _BimaModule {
	GObject __parent__;
	/*< public >*/
	gchar * id;
	gchar * name;
	gchar * description;
	gchar * parent_id;
};

/*
 * Class definition
 */
typedef struct _BimaModuleClass BimaModuleClass;
struct _BimaModuleClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	bima_module_get_type	(void);
gchar * 	bima_module_get_id	(BimaModule * self);
void 	bima_module_set_id	(BimaModule * self,
					gchar * val);
gchar * 	bima_module_get_name	(BimaModule * self);
void 	bima_module_set_name	(BimaModule * self,
					gchar * val);
gchar * 	bima_module_get_description	(BimaModule * self);
void 	bima_module_set_description	(BimaModule * self,
					gchar * val);
void 	bima_module_write_to_xml	(BimaModule * self,
					FILE * ofile);
BimaModule * 	bima_module_new	(void);
BimaModule * 	bima_module_new_with_id	(gchar * id,
					gchar * parent_id);

/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define BIMA_MODULE_PROP_ID(arg)    	"id", __extension__ ({gchar *z = (arg); z;})
#define BIMA_MODULE_GET_PROP_ID(arg)	"id", __extension__ ({gchar **z = (arg); z;})
#define BIMA_MODULE_PROP_NAME(arg)    	"name", __extension__ ({gchar *z = (arg); z;})
#define BIMA_MODULE_GET_PROP_NAME(arg)	"name", __extension__ ({gchar **z = (arg); z;})
#define BIMA_MODULE_PROP_DESCRIPTION(arg)    	"description", __extension__ ({gchar *z = (arg); z;})
#define BIMA_MODULE_GET_PROP_DESCRIPTION(arg)	"description", __extension__ ({gchar **z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define BIMA_MODULE_PROP_ID(arg)    	"id",(gchar *)(arg)
#define BIMA_MODULE_GET_PROP_ID(arg)	"id",(gchar **)(arg)
#define BIMA_MODULE_PROP_NAME(arg)    	"name",(gchar *)(arg)
#define BIMA_MODULE_GET_PROP_NAME(arg)	"name",(gchar **)(arg)
#define BIMA_MODULE_PROP_DESCRIPTION(arg)    	"description",(gchar *)(arg)
#define BIMA_MODULE_GET_PROP_DESCRIPTION(arg)	"description",(gchar **)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
