/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-foreign-key.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_FOREIGN_KEY(x)
#define SELF_CONST(x) BIMA_FOREIGN_KEY_CONST(x)
#define IS_SELF(x) BIMA_IS_FOREIGN_KEY(x)
#define TYPE_SELF BIMA_TYPE_FOREIGN_KEY
#define SELF_CLASS(x) BIMA_FOREIGN_KEY_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_FOREIGN_KEY_GET_CLASS(x)

/* self typedefs */
typedef BimaForeignKey Self;
typedef BimaForeignKeyClass SelfClass;

/* here are local prototypes */
static void bima_foreign_key_init (BimaForeignKey * o) G_GNUC_UNUSED;
static void bima_foreign_key_class_init (BimaForeignKeyClass * c) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_write_to_xml bima_foreign_key_write_to_xml
#define self_new bima_foreign_key_new
GType
bima_foreign_key_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaForeignKeyClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_foreign_key_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaForeignKey),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_foreign_key_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaForeignKey", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaForeignKey *)g_object_new(bima_foreign_key_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaForeignKey * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaForeignKey *
GET_NEW_VARG (const char *first, ...)
{
	BimaForeignKey *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaForeignKey *)g_object_new_valist (bima_foreign_key_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Foreign:Key::finalize"
	BimaForeignKey *self G_GNUC_UNUSED = BIMA_FOREIGN_KEY (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 54 "foreignkey.gob"
	if(self->pk_obj_id) { g_free ((gpointer) self->pk_obj_id); self->pk_obj_id = NULL; }
#line 98 "bima-foreign-key.c"
#define name (self->name)
#define VAR name
	{
#line 57 "foreignkey.gob"
	name = NULL;}
#line 104 "bima-foreign-key.c"
	memset(&name, 0, sizeof(name));
#undef VAR
#undef name
#define relation (self->relation)
#define VAR relation
	{
#line 60 "foreignkey.gob"
	relation = NULL;}
#line 113 "bima-foreign-key.c"
	memset(&relation, 0, sizeof(relation));
#undef VAR
#undef relation
}
#undef __GOB_FUNCTION__

static void 
bima_foreign_key_init (BimaForeignKey * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Foreign:Key::init"
#line 34 "foreignkey.gob"
	o->pk_obj_id = NULL;
#line 126 "bima-foreign-key.c"
#line 34 "foreignkey.gob"
	o->name = NULL;
#line 129 "bima-foreign-key.c"
#line 57 "foreignkey.gob"
	o->relation = NULL;
#line 132 "bima-foreign-key.c"
#line 60 "foreignkey.gob"
	o->relation_type = REL_NONE;
#line 135 "bima-foreign-key.c"
}
#undef __GOB_FUNCTION__
static void 
bima_foreign_key_class_init (BimaForeignKeyClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Foreign:Key::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__



#line 67 "foreignkey.gob"
void 
bima_foreign_key_write_to_xml (BimaForeignKey * self, FILE * ofile)
#line 155 "bima-foreign-key.c"
{
#define __GOB_FUNCTION__ "Bima:Foreign:Key::write_to_xml"
#line 67 "foreignkey.gob"
	g_return_if_fail (self != NULL);
#line 67 "foreignkey.gob"
	g_return_if_fail (BIMA_IS_FOREIGN_KEY (self));
#line 162 "bima-foreign-key.c"
{
#line 69 "foreignkey.gob"
	
		GList *list;

		switch (self->relation_type) {
			case REL_NONE:
				fprintf(ofile, "\t\t\t<ForeignKey primary_key_id=\"%s\" relation_type=\"REL_NONE\">\n", \ 
					self->pk_obj_id );
				break;
			case REL_1TO1:
				fprintf(ofile, "\t\t\t<ForeignKey primary_key_id=\"%s\" relation_type=\"REL_1TO1\">\n", \ 
					self->pk_obj_id );
				break;
			case REL_1TOM:
				fprintf(ofile, "\t\t\t<ForeignKey primary_key_id=\"%s\" relation_type=\"REL_1TOM\">\n", \ 
					self->pk_obj_id );
				break;
			case REL_MTO1:
				fprintf(ofile, "\t\t\t<ForeignKey primary_key_id=\"%s\" relation_type=\"REL_MTO1\">\n", \ 
					self->pk_obj_id );
				break;
			case REL_MTOM:
				fprintf(ofile, "\t\t\t<ForeignKey primary_key_id=\"%s\" relation_type=\"REL_MTOM\">\n", \ 
					self->pk_obj_id );
				break;
		}

		//if (self->description)
		//	fprintf(ofile, "\t\t<Description>%s</Description>", self->description);

		fprintf(ofile, "\t\t\t</ForeignKey>\n");
	}}
#line 196 "bima-foreign-key.c"
#undef __GOB_FUNCTION__

#line 101 "foreignkey.gob"
BimaForeignKey * 
bima_foreign_key_new (void)
#line 202 "bima-foreign-key.c"
{
#define __GOB_FUNCTION__ "Bima:Foreign:Key::new"
{
#line 103 "foreignkey.gob"
	
		return GET_NEW;
	}}
#line 210 "bima-foreign-key.c"
#undef __GOB_FUNCTION__
