/* Generated by GOB (v2.0.13)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include "bima-entity.h"

#ifndef __BIMA_PARTICIPATION_H__
#define __BIMA_PARTICIPATION_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define BIMA_TYPE_PARTICIPATION	(bima_participation_get_type())
#define BIMA_PARTICIPATION(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_participation_get_type(), BimaParticipation)
#define BIMA_PARTICIPATION_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_participation_get_type(), BimaParticipation const)
#define BIMA_PARTICIPATION_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), bima_participation_get_type(), BimaParticipationClass)
#define BIMA_IS_PARTICIPATION(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), bima_participation_get_type ())

#define BIMA_PARTICIPATION_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), bima_participation_get_type(), BimaParticipationClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BIMA_PARTICIPATION__
#define __TYPEDEF_BIMA_PARTICIPATION__
typedef struct _BimaParticipation BimaParticipation;
#endif
struct _BimaParticipation {
	GObject __parent__;
	/*< public >*/
	gboolean is_total;
	gint connection;
	gchar * entity_id;
	GObject * parent;
};

/*
 * Class definition
 */
typedef struct _BimaParticipationClass BimaParticipationClass;
struct _BimaParticipationClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	bima_participation_get_type	(void);
BimaParticipation * 	bima_participation_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
