/* Generated by GOB (v2.0.13)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include "bima-entity.h"

#ifndef __BIMA_CONNECTION_H__
#define __BIMA_CONNECTION_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define BIMA_TYPE_CONNECTION	(bima_connection_get_type())
#define BIMA_CONNECTION(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_connection_get_type(), BimaConnection)
#define BIMA_CONNECTION_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_connection_get_type(), BimaConnection const)
#define BIMA_CONNECTION_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), bima_connection_get_type(), BimaConnectionClass)
#define BIMA_IS_CONNECTION(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), bima_connection_get_type ())

#define BIMA_CONNECTION_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), bima_connection_get_type(), BimaConnectionClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BIMA_CONNECTION__
#define __TYPEDEF_BIMA_CONNECTION__
typedef struct _BimaConnection BimaConnection;
#endif
struct _BimaConnection {
	GObject __parent__;
	/*< public >*/
	gboolean is_total;
	gchar * entity_id;
	gint connection;
	BimaEntity * entity;
};

/*
 * Class definition
 */
typedef struct _BimaConnectionClass BimaConnectionClass;
struct _BimaConnectionClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	bima_connection_get_type	(void);
BimaConnection * 	bima_connection_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
