/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-template-form.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 32 "template-form.gob"


GList *
load_properties(xmlNodePtr xml_node ) {
	
	GList* list=NULL;
	BimaProperty *prop;
	xmlNodePtr xml_child_node;
	gchar *name, *type, *title;
	
	xml_child_node = xml_node->children;
	while ( xml_child_node != NULL ) {
		if (!xmlStrcmp(xml_child_node->name, (const xmlChar *)"Property")) {
			name = (gchar *) xmlGetProp(xml_child_node,"name");
			type = (gchar *) xmlGetProp(xml_child_node,"type");
			title = (gchar *) xmlGetProp(xml_child_node,"title");
			
			if ((name) && (type))
				prop = bima_property_new(name, title, type);
			//g_printf("add prop tmplt %s %s\n", prop->name, prop->type);
			list = g_list_append(list, (gpointer) prop);
		}
		xml_child_node = xml_child_node->next ;
	}
	return list;
}


#line 53 "bima-template-form.c"
/* self casting macros */
#define SELF(x) BIMA_TEMPLATE_FORM(x)
#define SELF_CONST(x) BIMA_TEMPLATE_FORM_CONST(x)
#define IS_SELF(x) BIMA_IS_TEMPLATE_FORM(x)
#define TYPE_SELF BIMA_TYPE_TEMPLATE_FORM
#define SELF_CLASS(x) BIMA_TEMPLATE_FORM_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_TEMPLATE_FORM_GET_CLASS(x)

/* self typedefs */
typedef BimaTemplateForm Self;
typedef BimaTemplateFormClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void bima_template_form_init (BimaTemplateForm * o) G_GNUC_UNUSED;
static void bima_template_form_class_init (BimaTemplateFormClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_ID
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_id bima_template_form_get_id
#define self_set_id bima_template_form_set_id
#define self_load_from_xml bima_template_form_load_from_xml
#define self_new bima_template_form_new
GType
bima_template_form_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaTemplateFormClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_template_form_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaTemplateForm),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_template_form_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaTemplateForm", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaTemplateForm *)g_object_new(bima_template_form_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaTemplateForm * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaTemplateForm *
GET_NEW_VARG (const char *first, ...)
{
	BimaTemplateForm *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaTemplateForm *)g_object_new_valist (bima_template_form_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Template:Form::finalize"
	BimaTemplateForm *self G_GNUC_UNUSED = BIMA_TEMPLATE_FORM (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 63 "template-form.gob"
	if(self->id) { g_free ((gpointer) self->id); self->id = NULL; }
#line 138 "bima-template-form.c"
#line 73 "template-form.gob"
	if(self->name) { g_free ((gpointer) self->name); self->name = NULL; }
#line 141 "bima-template-form.c"
#line 79 "template-form.gob"
	if(self->prefix) { g_free ((gpointer) self->prefix); self->prefix = NULL; }
#line 144 "bima-template-form.c"
#line 82 "template-form.gob"
	if(self->suffix) { g_free ((gpointer) self->suffix); self->suffix = NULL; }
#line 147 "bima-template-form.c"
#line 85 "template-form.gob"
	if(self->file_format) { g_free ((gpointer) self->file_format); self->file_format = NULL; }
#line 150 "bima-template-form.c"
#line 88 "template-form.gob"
	if(self->image_file) { g_free ((gpointer) self->image_file); self->image_file = NULL; }
#line 153 "bima-template-form.c"
#define template_file (self->template_file)
#define VAR template_file
	{
#line 93 "template-form.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_free(list->data);
			}
		}
#line 165 "bima-template-form.c"
	memset(&template_file, 0, sizeof(template_file));
#undef VAR
#undef template_file
#define properties (self->properties)
#define VAR properties
	{
#line 102 "template-form.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data);
					//g_free(list->data);
			}
		}
#line 181 "bima-template-form.c"
	memset(&properties, 0, sizeof(properties));
#undef VAR
#undef properties
}
#undef __GOB_FUNCTION__

static void 
bima_template_form_init (BimaTemplateForm * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Template:Form::init"
#line 32 "template-form.gob"
	o->id = NULL;
#line 194 "bima-template-form.c"
#line 32 "template-form.gob"
	o->name = NULL;
#line 197 "bima-template-form.c"
#line 32 "template-form.gob"
	o->prefix = NULL;
#line 200 "bima-template-form.c"
#line 32 "template-form.gob"
	o->suffix = NULL;
#line 203 "bima-template-form.c"
#line 32 "template-form.gob"
	o->file_format = NULL;
#line 206 "bima-template-form.c"
#line 32 "template-form.gob"
	o->image_file = NULL;
#line 209 "bima-template-form.c"
#line 32 "template-form.gob"
	o->template_file = NULL;
#line 212 "bima-template-form.c"
#line 93 "template-form.gob"
	o->properties = NULL;
#line 215 "bima-template-form.c"
}
#undef __GOB_FUNCTION__
static void 
bima_template_form_class_init (BimaTemplateFormClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Template:Form::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("id" /* name */,
		 "id" /* nick */,
		 "id of template form" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_ID,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Template:Form::set_property"
{
	BimaTemplateForm *self G_GNUC_UNUSED;

	self = BIMA_TEMPLATE_FORM (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 64 "template-form.gob"
{ char *old = self->id; self->id = g_value_dup_string (VAL); g_free (old); }
#line 261 "bima-template-form.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Template:Form::get_property"
{
	BimaTemplateForm *self G_GNUC_UNUSED;

	self = BIMA_TEMPLATE_FORM (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 64 "template-form.gob"
g_value_set_string (VAL, self->id);
#line 292 "bima-template-form.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 64 "template-form.gob"
gchar * 
bima_template_form_get_id (BimaTemplateForm * self)
#line 312 "bima-template-form.c"
{
#define __GOB_FUNCTION__ "Bima:Template:Form::get_id"
{
#line 64 "template-form.gob"
		gchar* val; g_object_get (G_OBJECT (self), "id", &val, NULL); return val;
}}
#line 319 "bima-template-form.c"
#undef __GOB_FUNCTION__

#line 64 "template-form.gob"
void 
bima_template_form_set_id (BimaTemplateForm * self, gchar * val)
#line 325 "bima-template-form.c"
{
#define __GOB_FUNCTION__ "Bima:Template:Form::set_id"
{
#line 64 "template-form.gob"
		g_object_set (G_OBJECT (self), "id", val, NULL);
}}
#line 332 "bima-template-form.c"
#undef __GOB_FUNCTION__

#line 112 "template-form.gob"
void 
bima_template_form_load_from_xml (BimaTemplateForm * self, xmlNodePtr xml_node)
#line 338 "bima-template-form.c"
{
#define __GOB_FUNCTION__ "Bima:Template:Form::load_from_xml"
#line 112 "template-form.gob"
	g_return_if_fail (self != NULL);
#line 112 "template-form.gob"
	g_return_if_fail (BIMA_IS_TEMPLATE_FORM (self));
#line 345 "bima-template-form.c"
{
#line 114 "template-form.gob"
	
		xmlNodePtr xml_child_node; 
		//gchar *tmp_str;
		xmlChar *xml_prop;
		
		if (xml_node != NULL) {
			if (self && xmlGetProp(xml_node,"name")) {
				self->id = xmlGetProp(xml_node,"id");
				self->name = xmlGetProp(xml_node,"name");
				//self->file = xmlGetProp(xml_node,"file");
				self->prefix = xmlGetProp(xml_node,"prefix");
				self->suffix = xmlGetProp(xml_node,"suffix");
				self->file_format = xmlGetProp(xml_node,"fileformat");
				self->image_file = xmlGetProp(xml_node,"image_file");
				
				xml_prop  = xmlGetProp(xml_node,"relation_type");
				if (xml_prop) {
					if (!xmlStrcmp(xml_prop, (const xmlChar *) "NONE")) {
						self->relation_type = REL_NONE;
					}
					else if (!xmlStrcmp(xml_prop, (const xmlChar *) "1TO1")) {
						self->relation_type = REL_1TO1;
					}
					else if (!xmlStrcmp(xml_prop, (const xmlChar *) "1TOM")) {
						self->relation_type = REL_1TOM;
					}
					else if (!xmlStrcmp(xml_prop, (const xmlChar *) "MTO1")) {
						self->relation_type = REL_MTO1;
					}
					else if ( (!xmlStrcmp(xml_prop, (const xmlChar *) "MTOM")) || (!xmlStrcmp(xml_prop, (const xmlChar *) "NTOM")) ){
						self->relation_type = REL_MTOM;
					}
					//g_printf("  rel type %s %d\n", xml_prop, self->relation_type);
				}
				xml_child_node = xml_node->children;
				while ( xml_child_node != NULL ) {
					if (!xmlStrcmp(xml_child_node->name, (const xmlChar *)"Template")) {
						self->template_file = g_list_append(self->template_file, xmlGetProp(xml_child_node,"file"));
						//g_print("%s\n",self->template_file->data);
					} else if (!xmlStrcmp(xml_child_node->name, (const xmlChar *)"Properties")) {
						self->properties = load_properties(xml_child_node);
						//g_print("num prop %d\n", g_list_length(self->properties));
					}
					
					xml_child_node = xml_child_node->next ;
				}
				
//				g_print("id : %s type %d %s \n", self->id , self->relation_type ,self->name) ;
			}
			//xml_child_node = xml_child_node->next;
		}
	}}
#line 400 "bima-template-form.c"
#undef __GOB_FUNCTION__

#line 167 "template-form.gob"
BimaTemplateForm * 
bima_template_form_new (void)
#line 406 "bima-template-form.c"
{
#define __GOB_FUNCTION__ "Bima:Template:Form::new"
{
#line 169 "template-form.gob"
	
		return GET_NEW;
	}}
#line 414 "bima-template-form.c"
#undef __GOB_FUNCTION__
