/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-query.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_QUERY(x)
#define SELF_CONST(x) BIMA_QUERY_CONST(x)
#define IS_SELF(x) BIMA_IS_QUERY(x)
#define TYPE_SELF BIMA_TYPE_QUERY
#define SELF_CLASS(x) BIMA_QUERY_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_QUERY_GET_CLASS(x)

/* self typedefs */
typedef BimaQuery Self;
typedef BimaQueryClass SelfClass;

/* here are local prototypes */
static void bima_query_init (BimaQuery * o) G_GNUC_UNUSED;
static void bima_query_class_init (BimaQueryClass * c) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_dump_tables bima_query_dump_tables
#define self_get_entity_alias bima_query_get_entity_alias
#define self_locate_field_attribute bima_query_locate_field_attribute
#define self_validate_fields bima_query_validate_fields
#define self_get_attribute_sub_query bima_query_get_attribute_sub_query
#define self_get_number_of_fields bima_query_get_number_of_fields
#define self_get_number_of_tables bima_query_get_number_of_tables
#define self_get_number_of_sub_query bima_query_get_number_of_sub_query
#define self_get_nth_table_in_table bima_query_get_nth_table_in_table
#define self_get_nth_table bima_query_get_nth_table
#define self_count_table_in_table bima_query_count_table_in_table
#define self_count_num_of_tables bima_query_count_num_of_tables
#define self_count_number_of_fields bima_query_count_number_of_fields
#define self_get_nth_attribute_sub bima_query_get_nth_attribute_sub
#define self_get_nth_attribute bima_query_get_nth_attribute
#define self_get_str bima_query_get_str
#define self_get_fields_str bima_query_get_fields_str
#define self_get_tables_str bima_query_get_tables_str
#define self_new bima_query_new
GType
bima_query_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaQueryClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_query_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaQuery),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_query_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaQuery", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaQuery *)g_object_new(bima_query_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaQuery * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaQuery *
GET_NEW_VARG (const char *first, ...)
{
	BimaQuery *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaQuery *)g_object_new_valist (bima_query_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Query::finalize"
	BimaQuery *self G_GNUC_UNUSED = BIMA_QUERY (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#define fields (self->fields)
#define VAR fields
	{
#line 33 "query.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) (list->data)); 
			}
			g_list_free(VAR);
			VAR = NULL;
		}
#line 126 "bima-query.c"
	memset(&fields, 0, sizeof(fields));
#undef VAR
#undef fields
#define tables (self->tables)
#define VAR tables
	{
#line 47 "query.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) (list->data)); 
			}
			g_list_free(VAR);			
			VAR = NULL;
		}
#line 143 "bima-query.c"
	memset(&tables, 0, sizeof(tables));
#undef VAR
#undef tables
#define groups (self->groups)
#define VAR groups
	{
#line 73 "query.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);			
			VAR = NULL;
		}
#line 160 "bima-query.c"
	memset(&groups, 0, sizeof(groups));
#undef VAR
#undef groups
#define orders (self->orders)
#define VAR orders
	{
#line 84 "query.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);			
			VAR = NULL;
		}
#line 177 "bima-query.c"
	memset(&orders, 0, sizeof(orders));
#undef VAR
#undef orders
#define wheres (self->wheres)
#define VAR wheres
	{
#line 95 "query.gob"
	 
			if (!wheres) 
				return ;
			g_object_unref((GObject *) wheres);
			wheres = NULL;
		}
#line 191 "bima-query.c"
	memset(&wheres, 0, sizeof(wheres));
#undef VAR
#undef wheres
#define havings (self->havings)
#define VAR havings
	{
#line 103 "query.gob"
	 
			if (!havings) 
				return ;
			g_object_unref((GObject *) havings);
			havings = NULL;
		}
#line 205 "bima-query.c"
	memset(&havings, 0, sizeof(havings));
#undef VAR
#undef havings
}
#undef __GOB_FUNCTION__

static void 
bima_query_init (BimaQuery * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Query::init"
#line 24 "query.gob"
	o->num_fields = 0;
#line 218 "bima-query.c"
#line 24 "query.gob"
	o->fields = NULL;
#line 221 "bima-query.c"
#line 33 "query.gob"
	o->num_tables = 0;
#line 224 "bima-query.c"
#line 33 "query.gob"
	o->num_sub_qry = 0;
#line 227 "bima-query.c"
#line 33 "query.gob"
	o->tables = NULL;
#line 230 "bima-query.c"
#line 58 "query.gob"
	o->groups = NULL;
#line 233 "bima-query.c"
#line 73 "query.gob"
	o->orders = NULL;
#line 236 "bima-query.c"
#line 94 "query.gob"
	o->wheres = NULL;
#line 239 "bima-query.c"
#line 102 "query.gob"
	o->havings = NULL;
#line 242 "bima-query.c"
}
#undef __GOB_FUNCTION__
static void 
bima_query_class_init (BimaQueryClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Query::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__



#line 57 "query.gob"
void 
bima_query_dump_tables (BimaQuery * self)
#line 262 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::dump_tables"
#line 57 "query.gob"
	g_return_if_fail (self != NULL);
#line 57 "query.gob"
	g_return_if_fail (BIMA_IS_QUERY (self));
#line 269 "bima-query.c"
{
#line 58 "query.gob"
	
		GList *list;
		BimaQueryTable *qry_tmp;
		
		if (!self) return ;
		for (list=g_list_first(self->tables);list != NULL; list = list->next){
			if (!list->data)
				break;
				
			qry_tmp = (BimaQueryTable *) (list->data);
			g_print("%s\n" , qry_tmp->table);
		}
	}}
#line 285 "bima-query.c"
#undef __GOB_FUNCTION__

#line 110 "query.gob"
gchar * 
bima_query_get_entity_alias (BimaQuery * self, BimaEntity * entity)
#line 291 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_entity_alias"
#line 110 "query.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 110 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (gchar * )0);
#line 298 "bima-query.c"
{
#line 112 "query.gob"
	
		GList *list;
		gchar *ostr=NULL;
		
		for (list=g_list_first(self->tables);list != NULL; list = list->next){
			if (list->data){
				ostr = bima_query_table_get_entity_alias((BimaQueryTable *) list->data,entity);
				if (ostr)
					return ostr;
			}
		}		
		return NULL;
	}}
#line 314 "bima-query.c"
#undef __GOB_FUNCTION__

#line 126 "query.gob"
BimaAttribute * 
bima_query_locate_field_attribute (BimaQuery * self, BimaQueryField * qry_field)
#line 320 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::locate_field_attribute"
#line 126 "query.gob"
	g_return_val_if_fail (self != NULL, (BimaAttribute * )0);
#line 126 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (BimaAttribute * )0);
#line 327 "bima-query.c"
{
#line 128 "query.gob"
	
		return NULL;
	}}
#line 333 "bima-query.c"
#undef __GOB_FUNCTION__

#line 136 "query.gob"
gint 
bima_query_validate_fields (BimaQuery * self)
#line 339 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::validate_fields"
#line 136 "query.gob"
	g_return_val_if_fail (self != NULL, (gint )0);
#line 136 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (gint )0);
#line 346 "bima-query.c"
{
#line 138 "query.gob"
	
		GList *flist, *tlist;
		BimaQueryField *qfield;
		gint err_num;
		gchar *star;
		star = g_strdup("*");
		err_num = 0;
		for (flist=g_list_first(self->fields);flist != NULL; flist = flist->next){
			if (flist->data){
				qfield = (BimaQueryField *) (flist->data) ;
				if (g_ascii_strcasecmp(star, qfield->field)) {
					for (tlist=g_list_first(self->tables);tlist != NULL; tlist = tlist->next){
						qfield->attribute = bima_query_table_validate_field((BimaQueryTable *) (tlist->data),qfield);
					}
				}
			}
		}
		g_free(star);
		return err_num;
	}}
#line 369 "bima-query.c"
#undef __GOB_FUNCTION__

#line 161 "query.gob"
BimaAttribute * 
bima_query_get_attribute_sub_query (BimaQuery * self, BimaQueryField * qfield)
#line 375 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_attribute_sub_query"
#line 161 "query.gob"
	g_return_val_if_fail (self != NULL, (BimaAttribute * )0);
#line 161 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (BimaAttribute * )0);
#line 382 "bima-query.c"
{
#line 163 "query.gob"
	
		GList *flist=NULL;
		BimaAttribute *attribute=NULL;
		BimaQueryField *sqfield;
		
		for (flist=g_list_first(self->fields);flist != NULL; flist = flist->next){
			if (flist->data){
				sqfield = (BimaQueryField *) (flist->data) ;
				if (sqfield->alias) {
					if (!g_ascii_strcasecmp(sqfield->alias,qfield->field))  
						attribute = sqfield->attribute;
				} 
				else if (!g_ascii_strcasecmp(sqfield->field,qfield->field))  
					attribute = sqfield->attribute;
			}
			if (attribute)
				return attribute;
		}
		return attribute;
	}}
#line 405 "bima-query.c"
#undef __GOB_FUNCTION__

#line 184 "query.gob"
gint 
bima_query_get_number_of_fields (BimaQuery * self)
#line 411 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_number_of_fields"
#line 184 "query.gob"
	g_return_val_if_fail (self != NULL, (gint )0);
#line 184 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (gint )0);
#line 418 "bima-query.c"
{
#line 185 "query.gob"
	
		return self->num_fields;
	}}
#line 424 "bima-query.c"
#undef __GOB_FUNCTION__

#line 189 "query.gob"
gint 
bima_query_get_number_of_tables (BimaQuery * self)
#line 430 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_number_of_tables"
#line 189 "query.gob"
	g_return_val_if_fail (self != NULL, (gint )0);
#line 189 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (gint )0);
#line 437 "bima-query.c"
{
#line 190 "query.gob"
	
		return self->num_tables;
	}}
#line 443 "bima-query.c"
#undef __GOB_FUNCTION__

#line 194 "query.gob"
gint 
bima_query_get_number_of_sub_query (BimaQuery * self)
#line 449 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_number_of_sub_query"
#line 194 "query.gob"
	g_return_val_if_fail (self != NULL, (gint )0);
#line 194 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (gint )0);
#line 456 "bima-query.c"
{
#line 195 "query.gob"
	
		return self->num_sub_qry;
	}}
#line 462 "bima-query.c"
#undef __GOB_FUNCTION__

#line 199 "query.gob"
BimaQueryTable * 
bima_query_get_nth_table_in_table (BimaQuery * self, gint n, gint * nth, BimaQueryTable * qtbl)
#line 468 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_nth_table_in_table"
#line 199 "query.gob"
	g_return_val_if_fail (self != NULL, (BimaQueryTable * )0);
#line 199 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (BimaQueryTable * )0);
#line 475 "bima-query.c"
{
#line 200 "query.gob"
	
		BimaQueryTable *qtb;
		
		if (qtbl->sub_query == NULL) {
			if (qtbl->table) {
				if ((*nth) == n)
					return qtbl;
			} else {
				if (qtbl->left_table) 
					qtb = bima_query_get_nth_table_in_table(self, n , nth,qtbl->left_table);
				if (qtb) 
					return qtb;
				if (qtbl->right_table) 
					qtb = bima_query_get_nth_table_in_table(self, n , nth,qtbl->right_table);
				if (qtb) 
					return qtb;
			}
			(*nth)++;
		}
		return NULL;
	}}
#line 499 "bima-query.c"
#undef __GOB_FUNCTION__

#line 222 "query.gob"
BimaQueryTable * 
bima_query_get_nth_table (BimaQuery * self, gint n)
#line 505 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_nth_table"
#line 222 "query.gob"
	g_return_val_if_fail (self != NULL, (BimaQueryTable * )0);
#line 222 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (BimaQueryTable * )0);
#line 512 "bima-query.c"
{
#line 223 "query.gob"
	
		GList *tlist ;
		gint nth;
		BimaQueryTable *qtable, *qtbl;
		nth = 0 ;
		for (tlist=g_list_first(self->tables);tlist != NULL; tlist = tlist->next){
			qtbl = NULL;			
			qtable = (BimaQueryTable *)(tlist->data);
			qtbl = bima_query_get_nth_table_in_table(self, n , &nth,qtable);
			if (qtbl) 
				return qtbl;
		}
		return NULL;
	}}
#line 529 "bima-query.c"
#undef __GOB_FUNCTION__

#line 238 "query.gob"
void 
bima_query_count_table_in_table (BimaQuery * self, BimaQueryTable * qtbl)
#line 535 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::count_table_in_table"
#line 238 "query.gob"
	g_return_if_fail (self != NULL);
#line 238 "query.gob"
	g_return_if_fail (BIMA_IS_QUERY (self));
#line 542 "bima-query.c"
{
#line 239 "query.gob"
	
		if (qtbl->sub_query) {
			self->num_sub_qry++;
			bima_query_count_num_of_tables(qtbl->sub_query);
		} else {
			if (qtbl->table) {
				self->num_tables++;
			} else {
				if (qtbl->left_table) 
					bima_query_count_table_in_table(self,qtbl->left_table);
				if (qtbl->right_table) 
					bima_query_count_table_in_table(self,qtbl->right_table);
			}
		}	
	}}
#line 560 "bima-query.c"
#undef __GOB_FUNCTION__

#line 255 "query.gob"
void 
bima_query_count_num_of_tables (BimaQuery * self)
#line 566 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::count_num_of_tables"
#line 255 "query.gob"
	g_return_if_fail (self != NULL);
#line 255 "query.gob"
	g_return_if_fail (BIMA_IS_QUERY (self));
#line 573 "bima-query.c"
{
#line 256 "query.gob"
	
		GList *tlist ;
		BimaQueryTable *qtable;
		for (tlist=g_list_first(self->tables);tlist != NULL; tlist = tlist->next){
			qtable = (BimaQueryTable *)(tlist->data);
			bima_query_count_table_in_table(self,qtable);
		}				
	}}
#line 584 "bima-query.c"
#undef __GOB_FUNCTION__

#line 265 "query.gob"
gint 
bima_query_count_number_of_fields (BimaQuery * self)
#line 590 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::count_number_of_fields"
#line 265 "query.gob"
	g_return_val_if_fail (self != NULL, (gint )0);
#line 265 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (gint )0);
#line 597 "bima-query.c"
{
#line 266 "query.gob"
	
		GList *qf_list, *tlist;
		BimaQueryField *qfield;
		BimaQueryTable *qtable;
		gchar *star;
		gint i,n;
		star = g_strdup("*");

		self->num_fields = 0 ;		

		for (qf_list=g_list_first(self->fields);qf_list != NULL; qf_list = qf_list->next){
			qfield = (BimaQueryField *)(qf_list->data);
			if ( !g_ascii_strcasecmp(star, qfield->field)) { //if a star *
				for (tlist=g_list_first(self->tables);tlist != NULL; tlist = tlist->next){
					qtable = (BimaQueryTable *)(tlist->data);
					self->num_fields += bima_query_table_count_number_of_fields(qtable, qfield->table);
				}
			} else { // a single field
				self->num_fields++;
				// also update num_fields in qtable
				// look belong to whom this field
				qtable=NULL;
				n = self->num_tables + self->num_sub_qry;
				for (i=0; i < n ; i++){
					qtable = bima_query_get_nth_table(self,i);
					if (qtable) {
						if ( ((qtable->alias) && (!g_ascii_strcasecmp(qtable->alias, qfield->table))) ||
							 ((!qtable->alias) && (qtable->table) && (!g_ascii_strcasecmp(qtable->table, qfield->table))) 
							) {
							qtable->num_fields++;
						}
					}
				}			
			}
		}
		g_free(star);
		return self->num_fields;
	}}
#line 638 "bima-query.c"
#undef __GOB_FUNCTION__

#line 305 "query.gob"
GObject * 
bima_query_get_nth_attribute_sub (BimaQuery * self, gint n)
#line 644 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_nth_attribute_sub"
#line 305 "query.gob"
	g_return_val_if_fail (self != NULL, (GObject * )0);
#line 305 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (GObject * )0);
#line 651 "bima-query.c"
{
#line 307 "query.gob"
	
		GObject *attribute=NULL;
		BimaQueryTable *qtbl = NULL;
		BimaQueryField *qfld = NULL;
		attribute = bima_query_get_nth_attribute(self, n, &qtbl, &qfld);
		return attribute;
	}}
#line 661 "bima-query.c"
#undef __GOB_FUNCTION__

#line 315 "query.gob"
GObject * 
bima_query_get_nth_attribute (BimaQuery * self, gint n, BimaQueryTable ** qtbl, BimaQueryField ** qfld)
#line 667 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_nth_attribute"
#line 315 "query.gob"
	g_return_val_if_fail (self != NULL, (GObject * )0);
#line 315 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (GObject * )0);
#line 674 "bima-query.c"
{
#line 317 "query.gob"
	
		GObject *attribute=NULL;
		GList *qf_list, *tlist;
		BimaQueryField *qfield;
		BimaQueryTable *qtable;
		gint nth;
		gchar *star;
		
		star = g_strdup("*");
		nth = 0 ;
		for (qf_list=g_list_first(self->fields);qf_list != NULL; qf_list = qf_list->next){
			if (( nth <= n ) && (attribute == NULL)) {
				qfield = (BimaQueryField *)(qf_list->data); 
				*qfld = qfield;
				if ( !g_ascii_strcasecmp(star, qfield->field)) { //if a star *
					for (tlist=g_list_first(self->tables);tlist != NULL; tlist = tlist->next){
						qtable = (BimaQueryTable *)(tlist->data);
						*qtbl = qtable;
						attribute = bima_query_table_get_nth_attribute(qtable, qfield->table,n, &nth, qtbl);
					}
				} else {  // a single field					
					if (nth == n)
						attribute = (GObject *) qfield->attribute;
					nth++;
				}
			} 
		}
		g_free(star);
		return (GObject *)attribute;
	}}
#line 707 "bima-query.c"
#undef __GOB_FUNCTION__

#line 348 "query.gob"
gchar * 
bima_query_get_str (BimaQuery * self)
#line 713 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_str"
#line 348 "query.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 348 "query.gob"
	g_return_val_if_fail (BIMA_IS_QUERY (self), (gchar * )0);
#line 720 "bima-query.c"
{
#line 350 "query.gob"
	
		gchar *ostr=NULL;
	
		if (self == NULL)
			return NULL;	
	
		if (self->fields && self->tables) {
			ostr = g_strconcat("SELECT ",bima_query_get_fields_str(self->fields),"\n",NULL);
			ostr = g_strconcat(ostr, "FROM ",bima_query_get_tables_str(self->tables),"\n",NULL);
			if (self->wheres) {
				ostr = g_strconcat(ostr, " WHERE ",bima_query_field_get_str(self->wheres),"\n",NULL);
			}
			if (self->groups) {
				ostr = g_strconcat(ostr, " GROUP BY ",bima_query_get_fields_str(self->groups),"\n",NULL);
			}
			if (self->havings) {
				ostr = g_strconcat(ostr, " HAVING ",bima_query_field_get_str(self->havings),"\n",NULL);
			}
			if (self->orders) {
				ostr = g_strconcat(ostr, " ORDER BY ",bima_query_get_fields_str(self->orders),"\n",NULL);
			}
		}
		//printf("%s",tmp_str);
		//g_free(tmp_str);	
		return ostr;	
	}}
#line 749 "bima-query.c"
#undef __GOB_FUNCTION__

#line 377 "query.gob"
gchar * 
bima_query_get_fields_str (GList * plist)
#line 755 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_fields_str"
{
#line 379 "query.gob"
	
		GList *list;
		BimaQueryField *qfield;
		gchar *ostr=NULL;
		
		for (list=g_list_first(plist);list != NULL; list = list->next){
			if (list->data) {
				qfield = (BimaQueryField *) list->data;
				if (!ostr) 
					ostr = bima_query_field_get_str(qfield);
				else
					ostr = g_strconcat(ostr,g_strdup_printf(", %s",bima_query_field_get_str(qfield),NULL));
			} 
		}
		return ostr;
	}}
#line 776 "bima-query.c"
#undef __GOB_FUNCTION__

#line 396 "query.gob"
gchar * 
bima_query_get_tables_str (GList * tlist)
#line 782 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::get_tables_str"
{
#line 398 "query.gob"
	
		GList *list;
		BimaQueryTable *qtable;
		gchar *ostr=NULL;
		
		for (list=g_list_first(tlist);list != NULL; list = list->next){
			if (list->data) {
				qtable = (BimaQueryTable *) list->data;
				if (!ostr) 
					ostr = bima_query_table_get_str(qtable);
				else
					ostr = g_strconcat(ostr,g_strdup_printf(", %s",bima_query_table_get_str(qtable),NULL));

			} 
		}
		return ostr;
	}}
#line 804 "bima-query.c"
#undef __GOB_FUNCTION__

#line 416 "query.gob"
BimaQuery * 
bima_query_new (void)
#line 810 "bima-query.c"
{
#define __GOB_FUNCTION__ "Bima:Query::new"
{
#line 418 "query.gob"
	
		return GET_NEW;
	}}
#line 818 "bima-query.c"
#undef __GOB_FUNCTION__
