/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-relation.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_RELATION(x)
#define SELF_CONST(x) BIMA_RELATION_CONST(x)
#define IS_SELF(x) BIMA_IS_RELATION(x)
#define TYPE_SELF BIMA_TYPE_RELATION
#define SELF_CLASS(x) BIMA_RELATION_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_RELATION_GET_CLASS(x)

/* self typedefs */
typedef BimaRelation Self;
typedef BimaRelationClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void bima_relation_init (BimaRelation * o) G_GNUC_UNUSED;
static void bima_relation_class_init (BimaRelationClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_ID,
	PROP_NAME,
	PROP_MODULE_ID
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_id bima_relation_get_id
#define self_set_id bima_relation_set_id
#define self_get_name bima_relation_get_name
#define self_set_name bima_relation_set_name
#define self_get_module_id bima_relation_get_module_id
#define self_set_module_id bima_relation_set_module_id
#define self_add_attribute bima_relation_add_attribute
#define self_get_num_of_attribute bima_relation_get_num_of_attribute
#define self_get_attributes bima_relation_get_attributes
#define self_add_foreign_key bima_relation_add_foreign_key
#define self_get_nth_attribute bima_relation_get_nth_attribute
#define self_add_connection bima_relation_add_connection
#define self_write_to_xml bima_relation_write_to_xml
#define self_new bima_relation_new
GType
bima_relation_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaRelationClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_relation_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaRelation),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_relation_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaRelation", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaRelation *)g_object_new(bima_relation_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaRelation * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaRelation *
GET_NEW_VARG (const char *first, ...)
{
	BimaRelation *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaRelation *)g_object_new_valist (bima_relation_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Relation::finalize"
	BimaRelation *self G_GNUC_UNUSED = BIMA_RELATION (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 32 "relation.gob"
	if(self->id) { g_free ((gpointer) self->id); self->id = NULL; }
#line 119 "bima-relation.c"
#line 41 "relation.gob"
	if(self->name) { g_free ((gpointer) self->name); self->name = NULL; }
#line 122 "bima-relation.c"
#line 50 "relation.gob"
	if(self->abbreviation) { g_free ((gpointer) self->abbreviation); self->abbreviation = NULL; }
#line 125 "bima-relation.c"
#line 52 "relation.gob"
	if(self->description) { g_free ((gpointer) self->description); self->description = NULL; }
#line 128 "bima-relation.c"
#line 55 "relation.gob"
	if(self->module_id) { g_free ((gpointer) self->module_id); self->module_id = NULL; }
#line 131 "bima-relation.c"
#define attributes (self->attributes)
#define VAR attributes
	{
#line 65 "relation.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 143 "bima-relation.c"
	memset(&attributes, 0, sizeof(attributes));
#undef VAR
#undef attributes
#define foreign_key (self->foreign_key)
#define VAR foreign_key
	{
#line 74 "relation.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 158 "bima-relation.c"
	memset(&foreign_key, 0, sizeof(foreign_key));
#undef VAR
#undef foreign_key
#line 84 "relation.gob"
	if(self->left_card) { g_free ((gpointer) self->left_card); self->left_card = NULL; }
#line 164 "bima-relation.c"
#line 86 "relation.gob"
	if(self->right_card) { g_free ((gpointer) self->right_card); self->right_card = NULL; }
#line 167 "bima-relation.c"
#define connections (self->connections)
#define VAR connections
	{
#line 92 "relation.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 179 "bima-relation.c"
	memset(&connections, 0, sizeof(connections));
#undef VAR
#undef connections
}
#undef __GOB_FUNCTION__

static void 
bima_relation_init (BimaRelation * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Relation::init"
#line 31 "relation.gob"
	o->id =  NULL ;
#line 192 "bima-relation.c"
#line 40 "relation.gob"
	o->name =  NULL ;
#line 195 "bima-relation.c"
#line 49 "relation.gob"
	o->abbreviation =  NULL ;
#line 198 "bima-relation.c"
#line 51 "relation.gob"
	o->description =  NULL ;
#line 201 "bima-relation.c"
#line 54 "relation.gob"
	o->module_id =  NULL ;
#line 204 "bima-relation.c"
#line 54 "relation.gob"
	o->attributes = NULL;
#line 207 "bima-relation.c"
#line 65 "relation.gob"
	o->num_of_attribute = 0;
#line 210 "bima-relation.c"
#line 65 "relation.gob"
	o->foreign_key = NULL;
#line 213 "bima-relation.c"
#line 74 "relation.gob"
	o->num_of_foreign_key = 0;
#line 216 "bima-relation.c"
#line 83 "relation.gob"
	o->left_card =  g_strdup("1");;
#line 219 "bima-relation.c"
#line 85 "relation.gob"
	o->right_card =  g_strdup("1");;
#line 222 "bima-relation.c"
#line 85 "relation.gob"
	o->is_rotated = FALSE;
#line 225 "bima-relation.c"
#line 85 "relation.gob"
	o->num_of_connection = 0;
#line 228 "bima-relation.c"
#line 85 "relation.gob"
	o->connections = NULL;
#line 231 "bima-relation.c"
}
#undef __GOB_FUNCTION__
static void 
bima_relation_class_init (BimaRelationClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Relation::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("id" /* name */,
		 "id" /* nick */,
		 "id of relation" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_ID,
		param_spec);
	param_spec = g_param_spec_string
		("name" /* name */,
		 "name" /* nick */,
		 "name of relation" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_NAME,
		param_spec);
	param_spec = g_param_spec_string
		("module_id" /* name */,
		 "module id" /* nick */,
		 "module of relation" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_MODULE_ID,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Relation::set_property"
{
	BimaRelation *self G_GNUC_UNUSED;

	self = BIMA_RELATION (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 33 "relation.gob"
{ char *old = self->id; self->id = g_value_dup_string (VAL); g_free (old); }
#line 295 "bima-relation.c"
		}
		break;
	case PROP_NAME:
		{
#line 42 "relation.gob"
{ char *old = self->name; self->name = g_value_dup_string (VAL); g_free (old); }
#line 302 "bima-relation.c"
		}
		break;
	case PROP_MODULE_ID:
		{
#line 56 "relation.gob"
{ char *old = self->module_id; self->module_id = g_value_dup_string (VAL); g_free (old); }
#line 309 "bima-relation.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Relation::get_property"
{
	BimaRelation *self G_GNUC_UNUSED;

	self = BIMA_RELATION (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 33 "relation.gob"
g_value_set_string (VAL, self->id);
#line 340 "bima-relation.c"
		}
		break;
	case PROP_NAME:
		{
#line 42 "relation.gob"
g_value_set_string (VAL, self->name);
#line 347 "bima-relation.c"
		}
		break;
	case PROP_MODULE_ID:
		{
#line 56 "relation.gob"
g_value_set_string (VAL, self->module_id);
#line 354 "bima-relation.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 33 "relation.gob"
gchar * 
bima_relation_get_id (BimaRelation * self)
#line 374 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::get_id"
{
#line 33 "relation.gob"
		gchar* val; g_object_get (G_OBJECT (self), "id", &val, NULL); return val;
}}
#line 381 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 33 "relation.gob"
void 
bima_relation_set_id (BimaRelation * self, gchar * val)
#line 387 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::set_id"
{
#line 33 "relation.gob"
		g_object_set (G_OBJECT (self), "id", val, NULL);
}}
#line 394 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 42 "relation.gob"
gchar * 
bima_relation_get_name (BimaRelation * self)
#line 400 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::get_name"
{
#line 42 "relation.gob"
		gchar* val; g_object_get (G_OBJECT (self), "name", &val, NULL); return val;
}}
#line 407 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 42 "relation.gob"
void 
bima_relation_set_name (BimaRelation * self, gchar * val)
#line 413 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::set_name"
{
#line 42 "relation.gob"
		g_object_set (G_OBJECT (self), "name", val, NULL);
}}
#line 420 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 56 "relation.gob"
gchar * 
bima_relation_get_module_id (BimaRelation * self)
#line 426 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::get_module_id"
{
#line 56 "relation.gob"
		gchar* val; g_object_get (G_OBJECT (self), "module_id", &val, NULL); return val;
}}
#line 433 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 56 "relation.gob"
void 
bima_relation_set_module_id (BimaRelation * self, gchar * val)
#line 439 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::set_module_id"
{
#line 56 "relation.gob"
		g_object_set (G_OBJECT (self), "module_id", val, NULL);
}}
#line 446 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 100 "relation.gob"
void 
bima_relation_add_attribute (BimaRelation * self, BimaAttribute * attribute)
#line 452 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::add_attribute"
#line 100 "relation.gob"
	g_return_if_fail (self != NULL);
#line 100 "relation.gob"
	g_return_if_fail (BIMA_IS_RELATION (self));
#line 459 "bima-relation.c"
{
#line 102 "relation.gob"
	
		//g_printf("%s : %s \n", self->name, attribute->name);
		self->attributes = g_list_append(self->attributes, (gpointer) attribute);
		attribute->parent = (GObject *) self;
		self->num_of_attribute++;
	}}
#line 468 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 109 "relation.gob"
int 
bima_relation_get_num_of_attribute (BimaRelation * self)
#line 474 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::get_num_of_attribute"
#line 109 "relation.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 109 "relation.gob"
	g_return_val_if_fail (BIMA_IS_RELATION (self), (int )0);
#line 481 "bima-relation.c"
{
#line 110 "relation.gob"
	
		return self->num_of_attribute; 
	}}
#line 487 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 114 "relation.gob"
GList * 
bima_relation_get_attributes (BimaRelation * self)
#line 493 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::get_attributes"
#line 114 "relation.gob"
	g_return_val_if_fail (self != NULL, (GList * )0);
#line 114 "relation.gob"
	g_return_val_if_fail (BIMA_IS_RELATION (self), (GList * )0);
#line 500 "bima-relation.c"
{
#line 115 "relation.gob"
	
		return self->attributes; 
	}}
#line 506 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 120 "relation.gob"
void 
bima_relation_add_foreign_key (BimaRelation * self, BimaForeignKey * fk)
#line 512 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::add_foreign_key"
#line 120 "relation.gob"
	g_return_if_fail (self != NULL);
#line 120 "relation.gob"
	g_return_if_fail (BIMA_IS_RELATION (self));
#line 519 "bima-relation.c"
{
#line 122 "relation.gob"
	
		self->foreign_key = g_list_append(self->foreign_key, (gpointer) fk);
		self->num_of_foreign_key++;
	}}
#line 526 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 129 "relation.gob"
GObject * 
bima_relation_get_nth_attribute (BimaRelation * self, gint n)
#line 532 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::get_nth_attribute"
#line 129 "relation.gob"
	g_return_val_if_fail (self != NULL, (GObject * )0);
#line 129 "relation.gob"
	g_return_val_if_fail (BIMA_IS_RELATION (self), (GObject * )0);
#line 539 "bima-relation.c"
{
#line 131 "relation.gob"
	
		GList *list=NULL;
		
		gint i;
		i=0;
		for (list=g_list_first(self->attributes);list != NULL; list = list->next){
			//g_printf("Ent %d of %d \n", i, n);
			if (i==n)
				return (GObject *) (list->data);
			i++;			
		}
		for (list=g_list_first(self->foreign_key);list != NULL; list = list->next){
			//g_printf("Ent %d of %d \n", i, n);
			if (i==n)
				return (GObject *) (list->data);
			i++;			
		}
		return NULL;
	}}
#line 561 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 151 "relation.gob"
void 
bima_relation_add_connection (BimaRelation * self, BimaConnection * conn)
#line 567 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::add_connection"
#line 151 "relation.gob"
	g_return_if_fail (self != NULL);
#line 151 "relation.gob"
	g_return_if_fail (BIMA_IS_RELATION (self));
#line 574 "bima-relation.c"
{
#line 153 "relation.gob"
	
		self->connections = g_list_append(self->connections, (gpointer) conn);
		self->num_of_connection++;
	}}
#line 581 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 158 "relation.gob"
void 
bima_relation_write_to_xml (BimaRelation * self, FILE * ofile)
#line 587 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::write_to_xml"
#line 158 "relation.gob"
	g_return_if_fail (self != NULL);
#line 158 "relation.gob"
	g_return_if_fail (BIMA_IS_RELATION (self));
#line 594 "bima-relation.c"
{
#line 160 "relation.gob"
	
		GList *list;

		fprintf(ofile, "\t<Relation id=\"%s\" name=\"%s\" module=\"%s\" abbreviation=\"%s\" left_card=\"%s\" right_card=\"%s\" is_rotated=\"%d\">\n", \ 
			self->id , self->name, self->module_id, self->abbreviation, self->left_card, self->right_card, self->is_rotated);

		//if (self->description)
		//	fprintf(ofile, "\t\t<Description>%s</Description>", self->description);
		
		if ( self->attributes) {
			fprintf(ofile, "\t\t<Attributes>\n");
			for (list=g_list_first(self->attributes);list != NULL; list = list->next){
				if (list->data) 
					bima_attribute_write_to_xml((BimaAttribute *) list->data, ofile);			
			}		
			fprintf(ofile, "\t\t</Attributes>\n");
		}

		if (self->foreign_key) {
			fprintf(ofile, "\t\t<ForeignKeys>\n");
			for (list=g_list_first(self->foreign_key);list != NULL; list = list->next){
				if (list->data) 
					bima_foreign_key_write_to_xml((BimaForeignKey *) list->data, ofile);			
			}
			fprintf(ofile, "\t\t</ForeignKeys>\n");
		}
		fprintf(ofile, "\t</Relation>\n");
	}}
#line 625 "bima-relation.c"
#undef __GOB_FUNCTION__

#line 189 "relation.gob"
BimaRelation * 
bima_relation_new (void)
#line 631 "bima-relation.c"
{
#define __GOB_FUNCTION__ "Bima:Relation::new"
{
#line 191 "relation.gob"
	
		return GET_NEW;
	}}
#line 639 "bima-relation.c"
#undef __GOB_FUNCTION__
