/* Generated by GOB (v2.0.13)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __BIMA_VIEW_H__
#define __BIMA_VIEW_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define BIMA_TYPE_VIEW	(bima_view_get_type())
#define BIMA_VIEW(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_view_get_type(), BimaView)
#define BIMA_VIEW_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_view_get_type(), BimaView const)
#define BIMA_VIEW_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), bima_view_get_type(), BimaViewClass)
#define BIMA_IS_VIEW(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), bima_view_get_type ())

#define BIMA_VIEW_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), bima_view_get_type(), BimaViewClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BIMA_VIEW__
#define __TYPEDEF_BIMA_VIEW__
typedef struct _BimaView BimaView;
#endif
struct _BimaView {
	GObject __parent__;
	/*< public >*/
	gchar * id;
	gchar * name;
	gchar * title;
	gchar * primary_obj_id;
	gchar * description;
	gchar * sql_text;
};

/*
 * Class definition
 */
typedef struct _BimaViewClass BimaViewClass;
struct _BimaViewClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	bima_view_get_type	(void);
gchar * 	bima_view_get_id	(BimaView * self);
void 	bima_view_set_id	(BimaView * self,
					gchar * val);
gchar * 	bima_view_get_name	(BimaView * self);
void 	bima_view_set_name	(BimaView * self,
					gchar * val);
gchar * 	bima_view_get_title	(BimaView * self);
void 	bima_view_set_title	(BimaView * self,
					gchar * val);
gchar * 	bima_view_get_primary_obj_id	(BimaView * self);
void 	bima_view_set_primary_obj_id	(BimaView * self,
					gchar * val);
gchar * 	bima_view_get_description	(BimaView * self);
void 	bima_view_set_description	(BimaView * self,
					gchar * val);
gchar * 	bima_view_get_sql_text	(BimaView * self);
void 	bima_view_set_sql_text	(BimaView * self,
					gchar * val);
BimaView * 	bima_view_new	(void);

/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define BIMA_VIEW_PROP_ID(arg)    	"id", __extension__ ({gchar *z = (arg); z;})
#define BIMA_VIEW_GET_PROP_ID(arg)	"id", __extension__ ({gchar **z = (arg); z;})
#define BIMA_VIEW_PROP_NAME(arg)    	"name", __extension__ ({gchar *z = (arg); z;})
#define BIMA_VIEW_GET_PROP_NAME(arg)	"name", __extension__ ({gchar **z = (arg); z;})
#define BIMA_VIEW_PROP_TITLE(arg)    	"title", __extension__ ({gchar *z = (arg); z;})
#define BIMA_VIEW_GET_PROP_TITLE(arg)	"title", __extension__ ({gchar **z = (arg); z;})
#define BIMA_VIEW_PROP_PRIMARY_OBJ_ID(arg)    	"primary_obj_id", __extension__ ({gchar *z = (arg); z;})
#define BIMA_VIEW_GET_PROP_PRIMARY_OBJ_ID(arg)	"primary_obj_id", __extension__ ({gchar **z = (arg); z;})
#define BIMA_VIEW_PROP_DESCRIPTION(arg)    	"description", __extension__ ({gchar *z = (arg); z;})
#define BIMA_VIEW_GET_PROP_DESCRIPTION(arg)	"description", __extension__ ({gchar **z = (arg); z;})
#define BIMA_VIEW_PROP_SQL_TEXT(arg)    	"sql_text", __extension__ ({gchar *z = (arg); z;})
#define BIMA_VIEW_GET_PROP_SQL_TEXT(arg)	"sql_text", __extension__ ({gchar **z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define BIMA_VIEW_PROP_ID(arg)    	"id",(gchar *)(arg)
#define BIMA_VIEW_GET_PROP_ID(arg)	"id",(gchar **)(arg)
#define BIMA_VIEW_PROP_NAME(arg)    	"name",(gchar *)(arg)
#define BIMA_VIEW_GET_PROP_NAME(arg)	"name",(gchar **)(arg)
#define BIMA_VIEW_PROP_TITLE(arg)    	"title",(gchar *)(arg)
#define BIMA_VIEW_GET_PROP_TITLE(arg)	"title",(gchar **)(arg)
#define BIMA_VIEW_PROP_PRIMARY_OBJ_ID(arg)    	"primary_obj_id",(gchar *)(arg)
#define BIMA_VIEW_GET_PROP_PRIMARY_OBJ_ID(arg)	"primary_obj_id",(gchar **)(arg)
#define BIMA_VIEW_PROP_DESCRIPTION(arg)    	"description",(gchar *)(arg)
#define BIMA_VIEW_GET_PROP_DESCRIPTION(arg)	"description",(gchar **)(arg)
#define BIMA_VIEW_PROP_SQL_TEXT(arg)    	"sql_text",(gchar *)(arg)
#define BIMA_VIEW_GET_PROP_SQL_TEXT(arg)	"sql_text",(gchar **)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
