/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-form.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_FORM(x)
#define SELF_CONST(x) BIMA_FORM_CONST(x)
#define IS_SELF(x) BIMA_IS_FORM(x)
#define TYPE_SELF BIMA_TYPE_FORM
#define SELF_CLASS(x) BIMA_FORM_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_FORM_GET_CLASS(x)

/* self typedefs */
typedef BimaForm Self;
typedef BimaFormClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void bima_form_init (BimaForm * o) G_GNUC_UNUSED;
static void bima_form_class_init (BimaFormClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_ID,
	PROP_NAME,
	PROP_TITLE,
	PROP_PRIMARY_OBJ_ID,
	PROP_DESCRIPTION,
	PROP_SQL_TEXT
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_id bima_form_get_id
#define self_set_id bima_form_set_id
#define self_get_name bima_form_get_name
#define self_set_name bima_form_set_name
#define self_get_title bima_form_get_title
#define self_set_title bima_form_set_title
#define self_get_primary_obj_id bima_form_get_primary_obj_id
#define self_set_primary_obj_id bima_form_set_primary_obj_id
#define self_get_description bima_form_get_description
#define self_set_description bima_form_set_description
#define self_get_sql_text bima_form_get_sql_text
#define self_set_sql_text bima_form_set_sql_text
#define self_copy_properties bima_form_copy_properties
#define self_new bima_form_new
GType
bima_form_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaFormClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_form_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaForm),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_form_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaForm", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaForm *)g_object_new(bima_form_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaForm * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaForm *
GET_NEW_VARG (const char *first, ...)
{
	BimaForm *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaForm *)g_object_new_valist (bima_form_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Form::finalize"
	BimaForm *self G_GNUC_UNUSED = BIMA_FORM (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 31 "form.gob"
	if(self->id) { g_free ((gpointer) self->id); self->id = NULL; }
#line 122 "bima-form.c"
#line 40 "form.gob"
	if(self->name) { g_free ((gpointer) self->name); self->name = NULL; }
#line 125 "bima-form.c"
#line 50 "form.gob"
	if(self->title) { g_free ((gpointer) self->title); self->title = NULL; }
#line 128 "bima-form.c"
#line 60 "form.gob"
	if(self->primary_obj_id) { g_free ((gpointer) self->primary_obj_id); self->primary_obj_id = NULL; }
#line 131 "bima-form.c"
#line 70 "form.gob"
	if(self->description) { g_free ((gpointer) self->description); self->description = NULL; }
#line 134 "bima-form.c"
#line 80 "form.gob"
	if(self->sql_text) { g_free ((gpointer) self->sql_text); self->sql_text = NULL; }
#line 137 "bima-form.c"
#line 90 "form.gob"
	if(self->template_id) { g_free ((gpointer) self->template_id); self->template_id = NULL; }
#line 140 "bima-form.c"
#line 93 "form.gob"
	if(self->module_id) { g_free ((gpointer) self->module_id); self->module_id = NULL; }
#line 143 "bima-form.c"
#define properties (self->properties)
#define VAR properties
	{
#line 97 "form.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data);
			}
		}
#line 155 "bima-form.c"
	memset(&properties, 0, sizeof(properties));
#undef VAR
#undef properties
}
#undef __GOB_FUNCTION__

static void 
bima_form_init (BimaForm * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Form::init"
#line 30 "form.gob"
	o->id =  NULL ;
#line 168 "bima-form.c"
#line 39 "form.gob"
	o->name =  NULL ;
#line 171 "bima-form.c"
#line 39 "form.gob"
	o->title = NULL;
#line 174 "bima-form.c"
#line 59 "form.gob"
	o->primary_obj_id =  NULL ;
#line 177 "bima-form.c"
#line 69 "form.gob"
	o->description =  NULL ;
#line 180 "bima-form.c"
#line 79 "form.gob"
	o->sql_text =  NULL ;
#line 183 "bima-form.c"
#line 89 "form.gob"
	o->template_id =  NULL ;
#line 186 "bima-form.c"
#line 92 "form.gob"
	o->module_id =  NULL ;
#line 189 "bima-form.c"
#line 92 "form.gob"
	o->properties = NULL;
#line 192 "bima-form.c"
}
#undef __GOB_FUNCTION__
static void 
bima_form_class_init (BimaFormClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Form::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("id" /* name */,
		 "id" /* nick */,
		 "id of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_ID,
		param_spec);
	param_spec = g_param_spec_string
		("name" /* name */,
		 "name" /* nick */,
		 "name of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_NAME,
		param_spec);
	param_spec = g_param_spec_string
		("title" /* name */,
		 "title" /* nick */,
		 "title of attribute" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_TITLE,
		param_spec);
	param_spec = g_param_spec_string
		("primary_obj_id" /* name */,
		 "primary_obj_id" /* nick */,
		 "id of obj" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_PRIMARY_OBJ_ID,
		param_spec);
	param_spec = g_param_spec_string
		("description" /* name */,
		 "description" /* nick */,
		 "description of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DESCRIPTION,
		param_spec);
	param_spec = g_param_spec_string
		("sql_text" /* name */,
		 "sql_text" /* nick */,
		 "sql_text of view" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_SQL_TEXT,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Form::set_property"
{
	BimaForm *self G_GNUC_UNUSED;

	self = BIMA_FORM (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 32 "form.gob"
{ char *old = self->id; self->id = g_value_dup_string (VAL); g_free (old); }
#line 283 "bima-form.c"
		}
		break;
	case PROP_NAME:
		{
#line 41 "form.gob"
{ char *old = self->name; self->name = g_value_dup_string (VAL); g_free (old); }
#line 290 "bima-form.c"
		}
		break;
	case PROP_TITLE:
		{
#line 51 "form.gob"
{ char *old = self->title; self->title = g_value_dup_string (VAL); g_free (old); }
#line 297 "bima-form.c"
		}
		break;
	case PROP_PRIMARY_OBJ_ID:
		{
#line 61 "form.gob"
{ char *old = self->primary_obj_id; self->primary_obj_id = g_value_dup_string (VAL); g_free (old); }
#line 304 "bima-form.c"
		}
		break;
	case PROP_DESCRIPTION:
		{
#line 71 "form.gob"
{ char *old = self->description; self->description = g_value_dup_string (VAL); g_free (old); }
#line 311 "bima-form.c"
		}
		break;
	case PROP_SQL_TEXT:
		{
#line 81 "form.gob"
{ char *old = self->sql_text; self->sql_text = g_value_dup_string (VAL); g_free (old); }
#line 318 "bima-form.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Form::get_property"
{
	BimaForm *self G_GNUC_UNUSED;

	self = BIMA_FORM (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 32 "form.gob"
g_value_set_string (VAL, self->id);
#line 349 "bima-form.c"
		}
		break;
	case PROP_NAME:
		{
#line 41 "form.gob"
g_value_set_string (VAL, self->name);
#line 356 "bima-form.c"
		}
		break;
	case PROP_TITLE:
		{
#line 51 "form.gob"
g_value_set_string (VAL, self->title);
#line 363 "bima-form.c"
		}
		break;
	case PROP_PRIMARY_OBJ_ID:
		{
#line 61 "form.gob"
g_value_set_string (VAL, self->primary_obj_id);
#line 370 "bima-form.c"
		}
		break;
	case PROP_DESCRIPTION:
		{
#line 71 "form.gob"
g_value_set_string (VAL, self->description);
#line 377 "bima-form.c"
		}
		break;
	case PROP_SQL_TEXT:
		{
#line 81 "form.gob"
g_value_set_string (VAL, self->sql_text);
#line 384 "bima-form.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 32 "form.gob"
gchar * 
bima_form_get_id (BimaForm * self)
#line 404 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::get_id"
{
#line 32 "form.gob"
		gchar* val; g_object_get (G_OBJECT (self), "id", &val, NULL); return val;
}}
#line 411 "bima-form.c"
#undef __GOB_FUNCTION__

#line 32 "form.gob"
void 
bima_form_set_id (BimaForm * self, gchar * val)
#line 417 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::set_id"
{
#line 32 "form.gob"
		g_object_set (G_OBJECT (self), "id", val, NULL);
}}
#line 424 "bima-form.c"
#undef __GOB_FUNCTION__

#line 41 "form.gob"
gchar * 
bima_form_get_name (BimaForm * self)
#line 430 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::get_name"
{
#line 41 "form.gob"
		gchar* val; g_object_get (G_OBJECT (self), "name", &val, NULL); return val;
}}
#line 437 "bima-form.c"
#undef __GOB_FUNCTION__

#line 41 "form.gob"
void 
bima_form_set_name (BimaForm * self, gchar * val)
#line 443 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::set_name"
{
#line 41 "form.gob"
		g_object_set (G_OBJECT (self), "name", val, NULL);
}}
#line 450 "bima-form.c"
#undef __GOB_FUNCTION__

#line 51 "form.gob"
gchar * 
bima_form_get_title (BimaForm * self)
#line 456 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::get_title"
{
#line 51 "form.gob"
		gchar* val; g_object_get (G_OBJECT (self), "title", &val, NULL); return val;
}}
#line 463 "bima-form.c"
#undef __GOB_FUNCTION__

#line 51 "form.gob"
void 
bima_form_set_title (BimaForm * self, gchar * val)
#line 469 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::set_title"
{
#line 51 "form.gob"
		g_object_set (G_OBJECT (self), "title", val, NULL);
}}
#line 476 "bima-form.c"
#undef __GOB_FUNCTION__

#line 61 "form.gob"
gchar * 
bima_form_get_primary_obj_id (BimaForm * self)
#line 482 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::get_primary_obj_id"
{
#line 61 "form.gob"
		gchar* val; g_object_get (G_OBJECT (self), "primary_obj_id", &val, NULL); return val;
}}
#line 489 "bima-form.c"
#undef __GOB_FUNCTION__

#line 61 "form.gob"
void 
bima_form_set_primary_obj_id (BimaForm * self, gchar * val)
#line 495 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::set_primary_obj_id"
{
#line 61 "form.gob"
		g_object_set (G_OBJECT (self), "primary_obj_id", val, NULL);
}}
#line 502 "bima-form.c"
#undef __GOB_FUNCTION__

#line 71 "form.gob"
gchar * 
bima_form_get_description (BimaForm * self)
#line 508 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::get_description"
{
#line 71 "form.gob"
		gchar* val; g_object_get (G_OBJECT (self), "description", &val, NULL); return val;
}}
#line 515 "bima-form.c"
#undef __GOB_FUNCTION__

#line 71 "form.gob"
void 
bima_form_set_description (BimaForm * self, gchar * val)
#line 521 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::set_description"
{
#line 71 "form.gob"
		g_object_set (G_OBJECT (self), "description", val, NULL);
}}
#line 528 "bima-form.c"
#undef __GOB_FUNCTION__

#line 81 "form.gob"
gchar * 
bima_form_get_sql_text (BimaForm * self)
#line 534 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::get_sql_text"
{
#line 81 "form.gob"
		gchar* val; g_object_get (G_OBJECT (self), "sql_text", &val, NULL); return val;
}}
#line 541 "bima-form.c"
#undef __GOB_FUNCTION__

#line 81 "form.gob"
void 
bima_form_set_sql_text (BimaForm * self, gchar * val)
#line 547 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::set_sql_text"
{
#line 81 "form.gob"
		g_object_set (G_OBJECT (self), "sql_text", val, NULL);
}}
#line 554 "bima-form.c"
#undef __GOB_FUNCTION__

#line 105 "form.gob"
void 
bima_form_copy_properties (BimaForm * self, GList * properties)
#line 560 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::copy_properties"
#line 105 "form.gob"
	g_return_if_fail (self != NULL);
#line 105 "form.gob"
	g_return_if_fail (BIMA_IS_FORM (self));
#line 567 "bima-form.c"
{
#line 107 "form.gob"
	
		GList *list;
		BimaProperty *prop;

		for (list=g_list_first(properties);list != NULL; list = list->next){
			if (list->data) {
				prop = bima_property_copy( (BimaProperty *)(list->data) );
				self->properties = g_list_append(self->properties, (gpointer) prop);			
			}
		}
	}}
#line 581 "bima-form.c"
#undef __GOB_FUNCTION__

#line 119 "form.gob"
BimaForm * 
bima_form_new (void)
#line 587 "bima-form.c"
{
#define __GOB_FUNCTION__ "Bima:Form::new"
{
#line 121 "form.gob"
	
		return GET_NEW;
	}}
#line 595 "bima-form.c"
#undef __GOB_FUNCTION__
