/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-query-field.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_QUERY_FIELD(x)
#define SELF_CONST(x) BIMA_QUERY_FIELD_CONST(x)
#define IS_SELF(x) BIMA_IS_QUERY_FIELD(x)
#define TYPE_SELF BIMA_TYPE_QUERY_FIELD
#define SELF_CLASS(x) BIMA_QUERY_FIELD_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_QUERY_FIELD_GET_CLASS(x)

/* self typedefs */
typedef BimaQueryField Self;
typedef BimaQueryFieldClass SelfClass;

/* here are local prototypes */
static void bima_query_field_init (BimaQueryField * o) G_GNUC_UNUSED;
static void bima_query_field_class_init (BimaQueryFieldClass * c) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_str bima_query_field_get_str
#define self_new bima_query_field_new
GType
bima_query_field_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaQueryFieldClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_query_field_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaQueryField),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_query_field_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaQueryField", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaQueryField *)g_object_new(bima_query_field_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaQueryField * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaQueryField *
GET_NEW_VARG (const char *first, ...)
{
	BimaQueryField *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaQueryField *)g_object_new_valist (bima_query_field_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Query:Field::finalize"
	BimaQueryField *self G_GNUC_UNUSED = BIMA_QUERY_FIELD (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 9 "query-field.gob"
	if(self->table) { g_free ((gpointer) self->table); self->table = NULL; }
#line 98 "bima-query-field.c"
#line 11 "query-field.gob"
	if(self->field) { g_free ((gpointer) self->field); self->field = NULL; }
#line 101 "bima-query-field.c"
#line 13 "query-field.gob"
	if(self->alias) { g_free ((gpointer) self->alias); self->alias = NULL; }
#line 104 "bima-query-field.c"
#define left_field (self->left_field)
#define VAR left_field
	{
#line 19 "query-field.gob"
	 
			if (!left_field) 
				return ;
			g_object_unref((GObject *) left_field);
		}
#line 114 "bima-query-field.c"
	memset(&left_field, 0, sizeof(left_field));
#undef VAR
#undef left_field
#define right_field (self->right_field)
#define VAR right_field
	{
#line 26 "query-field.gob"
	 
			if (!right_field) 
				return ;
			g_object_unref((GObject *) right_field);
		}
#line 127 "bima-query-field.c"
	memset(&right_field, 0, sizeof(right_field));
#undef VAR
#undef right_field
#define attribute (self->attribute)
#define VAR attribute
	{
#line 33 "query-field.gob"
	
			attribute = NULL;
		}
#line 138 "bima-query-field.c"
	memset(&attribute, 0, sizeof(attribute));
#undef VAR
#undef attribute
}
#undef __GOB_FUNCTION__

static void 
bima_query_field_init (BimaQueryField * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Query:Field::init"
#line 8 "query-field.gob"
	o->table =  NULL ;
#line 151 "bima-query-field.c"
#line 10 "query-field.gob"
	o->field =  NULL ;
#line 154 "bima-query-field.c"
#line 12 "query-field.gob"
	o->alias =  NULL ;
#line 157 "bima-query-field.c"
#line 12 "query-field.gob"
	o->sort_type = 0;
#line 160 "bima-query-field.c"
#line 12 "query-field.gob"
	o->opr_type = 0;
#line 163 "bima-query-field.c"
#line 18 "query-field.gob"
	o->left_field = NULL;
#line 166 "bima-query-field.c"
#line 25 "query-field.gob"
	o->right_field = NULL;
#line 169 "bima-query-field.c"
#line 26 "query-field.gob"
	o->attribute = NULL;
#line 172 "bima-query-field.c"
}
#undef __GOB_FUNCTION__
static void 
bima_query_field_class_init (BimaQueryFieldClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Query:Field::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__



#line 37 "query-field.gob"
gchar * 
bima_query_field_get_str (BimaQueryField * self)
#line 192 "bima-query-field.c"
{
#define __GOB_FUNCTION__ "Bima:Query:Field::get_str"
#line 37 "query-field.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 37 "query-field.gob"
	g_return_val_if_fail (BIMA_IS_QUERY_FIELD (self), (gchar * )0);
#line 199 "bima-query-field.c"
{
#line 39 "query-field.gob"
	
		gchar *ostr=NULL;

		if (self->opr_type == 0) {
			if (self->table) 
				ostr = g_strdup_printf("%s.%s",self->table,self->field); 
			else
				ostr = g_strdup(self->field); 
		} 
		else if (self->opr_type < 100) {
			ostr = bima_query_field_get_str(self->left_field);
			switch (self->opr_type) {
				case 1: ostr = g_strconcat(ostr,"=",NULL); break;
				case 2: ostr = g_strconcat(ostr,"+",NULL); break;
				case 3: ostr = g_strconcat(ostr,"-",NULL); break;
				case 4: ostr = g_strconcat(ostr,"*",NULL); break;
				case 5: ostr = g_strconcat(ostr,"/",NULL); break;
				case 6: ostr = g_strconcat(ostr," AND ",NULL); break;
				case 7: ostr = g_strconcat(ostr," OR ",NULL); break;
			}		
			ostr = g_strconcat(ostr,bima_query_field_get_str(self->right_field),NULL);
		} 
		else {
			switch (self->opr_type) {
				case 100: ostr = g_strdup_printf("SUM(");  break;
				case 101: ostr = g_strdup_printf("COUNT("); break;
				case 102: ostr = g_strdup_printf("AVG(");  break; 
				case 103: ostr = g_strdup_printf("MAX(");  break;
				case 104: ostr = g_strdup_printf("MIN(");  break;
				case 105: ostr = g_strdup_printf("STDDEV(");  break;
				case 106: ostr = g_strdup_printf("VARIANCE(");  break;
			}
			ostr = g_strconcat(ostr,bima_query_field_get_str(self->right_field),")",NULL);
		}
	
		if (self->alias) 
			ostr = g_strconcat(ostr,g_strdup_printf(" AS %s",self->alias),NULL);
		
		return ostr;		
	}}
#line 242 "bima-query-field.c"
#undef __GOB_FUNCTION__

#line 80 "query-field.gob"
BimaQueryField * 
bima_query_field_new (void)
#line 248 "bima-query-field.c"
{
#define __GOB_FUNCTION__ "Bima:Query:Field::new"
{
#line 82 "query-field.gob"
	
		return GET_NEW;
	}}
#line 256 "bima-query-field.c"
#undef __GOB_FUNCTION__
