/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-app-data.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_APP_DATA(x)
#define SELF_CONST(x) BIMA_APP_DATA_CONST(x)
#define IS_SELF(x) BIMA_IS_APP_DATA(x)
#define TYPE_SELF BIMA_TYPE_APP_DATA
#define SELF_CLASS(x) BIMA_APP_DATA_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_APP_DATA_GET_CLASS(x)

/* self typedefs */
typedef BimaAppData Self;
typedef BimaAppDataClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void bima_app_data_init (BimaAppData * o) G_GNUC_UNUSED;
static void bima_app_data_class_init (BimaAppDataClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_PROJECT_NAME,
	PROP_VERSION,
	PROP_AUTHOR,
	PROP_DB_TYPE,
	PROP_DB_NAME,
	PROP_DB_USER_NAME,
	PROP_DB_USER_PASS
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_project_name bima_app_data_get_project_name
#define self_set_project_name bima_app_data_set_project_name
#define self_get_version bima_app_data_get_version
#define self_set_version bima_app_data_set_version
#define self_get_author bima_app_data_get_author
#define self_set_author bima_app_data_set_author
#define self_get_db_type bima_app_data_get_db_type
#define self_set_db_type bima_app_data_set_db_type
#define self_get_db_name bima_app_data_get_db_name
#define self_set_db_name bima_app_data_set_db_name
#define self_get_db_user_name bima_app_data_get_db_user_name
#define self_set_db_user_name bima_app_data_set_db_user_name
#define self_get_db_user_pass bima_app_data_get_db_user_pass
#define self_set_db_user_pass bima_app_data_set_db_user_pass
#define self_parse_file_diagram bima_app_data_parse_file_diagram
#define self_add_module bima_app_data_add_module
#define self_delete_module bima_app_data_delete_module
#define self_create_and_add_module bima_app_data_create_and_add_module
#define self_add_entity bima_app_data_add_entity
#define self_find_entity bima_app_data_find_entity
#define self_add_relation bima_app_data_add_relation
#define self_find_relation bima_app_data_find_relation
#define self_add_view bima_app_data_add_view
#define self_create_new_view bima_app_data_create_new_view
#define self_delete_view bima_app_data_delete_view
#define self_add_report bima_app_data_add_report
#define self_create_new_report bima_app_data_create_new_report
#define self_delete_report bima_app_data_delete_report
#define self_add_form bima_app_data_add_form
#define self_create_new_form bima_app_data_create_new_form
#define self_delete_form bima_app_data_delete_form
#define self_populate_views bima_app_data_populate_views
#define self_populate_forms bima_app_data_populate_forms
#define self_write_to_xml bima_app_data_write_to_xml
#define self_new bima_app_data_new
GType
bima_app_data_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaAppDataClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_app_data_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaAppData),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_app_data_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaAppData", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaAppData *)g_object_new(bima_app_data_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaAppData * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaAppData *
GET_NEW_VARG (const char *first, ...)
{
	BimaAppData *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaAppData *)g_object_new_valist (bima_app_data_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:App:Data::finalize"
	BimaAppData *self G_GNUC_UNUSED = BIMA_APP_DATA (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 63 "appdata.gob"
	if(self->source_file) { g_free ((gpointer) self->source_file); self->source_file = NULL; }
#line 144 "bima-app-data.c"
#line 65 "appdata.gob"
	if(self->output_dir) { g_free ((gpointer) self->output_dir); self->output_dir = NULL; }
#line 147 "bima-app-data.c"
#line 76 "appdata.gob"
	if(self->project_name) { g_free ((gpointer) self->project_name); self->project_name = NULL; }
#line 150 "bima-app-data.c"
#line 86 "appdata.gob"
	if(self->version) { g_free ((gpointer) self->version); self->version = NULL; }
#line 153 "bima-app-data.c"
#line 96 "appdata.gob"
	if(self->author) { g_free ((gpointer) self->author); self->author = NULL; }
#line 156 "bima-app-data.c"
#line 115 "appdata.gob"
	if(self->db_name) { g_free ((gpointer) self->db_name); self->db_name = NULL; }
#line 159 "bima-app-data.c"
#line 125 "appdata.gob"
	if(self->db_user_name) { g_free ((gpointer) self->db_user_name); self->db_user_name = NULL; }
#line 162 "bima-app-data.c"
#line 135 "appdata.gob"
	if(self->db_user_pass) { g_free ((gpointer) self->db_user_pass); self->db_user_pass = NULL; }
#line 165 "bima-app-data.c"
#define modules (self->modules)
#define VAR modules
	{
#line 145 "appdata.gob"
	
			GList *list;
			//g_print("destroy modules\n");
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);
			VAR = NULL;
		}
#line 180 "bima-app-data.c"
	memset(&modules, 0, sizeof(modules));
#undef VAR
#undef modules
#define entities (self->entities)
#define VAR entities
	{
#line 158 "appdata.gob"
	
			GList *list;
			//g_print("destroy entites\n");
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);
			VAR = NULL;
		}
#line 198 "bima-app-data.c"
	memset(&entities, 0, sizeof(entities));
#undef VAR
#undef entities
#define relations (self->relations)
#define VAR relations
	{
#line 170 "appdata.gob"
	
			GList *list;
			//g_print("destroy relations\n");			
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);
			VAR = NULL;
		}
#line 216 "bima-app-data.c"
	memset(&relations, 0, sizeof(relations));
#undef VAR
#undef relations
#define views (self->views)
#define VAR views
	{
#line 182 "appdata.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);
			VAR = NULL;			
		}
#line 233 "bima-app-data.c"
	memset(&views, 0, sizeof(views));
#undef VAR
#undef views
#define reports (self->reports)
#define VAR reports
	{
#line 194 "appdata.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);
			VAR = NULL;			
		}
#line 250 "bima-app-data.c"
	memset(&reports, 0, sizeof(reports));
#undef VAR
#undef reports
#define forms (self->forms)
#define VAR forms
	{
#line 206 "appdata.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
			g_list_free(VAR);
			VAR = NULL;			
		}
#line 267 "bima-app-data.c"
	memset(&forms, 0, sizeof(forms));
#undef VAR
#undef forms
#define template (self->template)
#define VAR template
	{
#line 217 "appdata.gob"
	 
			if (template != NULL)
				g_object_unref((GObject *) template);
		}
#line 279 "bima-app-data.c"
	memset(&template, 0, sizeof(template));
#undef VAR
#undef template
#define query (self->query)
#define VAR query
	{
#line 223 "appdata.gob"
	 
			if (query != NULL) 
				g_object_unref((GObject *) query);
		}
#line 291 "bima-app-data.c"
	memset(&query, 0, sizeof(query));
#undef VAR
#undef query
}
#undef __GOB_FUNCTION__

static void 
bima_app_data_init (BimaAppData * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:App:Data::init"
#line 46 "appdata.gob"
	o->source_file = NULL;
#line 304 "bima-app-data.c"
#line 46 "appdata.gob"
	o->output_dir = NULL;
#line 307 "bima-app-data.c"
#line 46 "appdata.gob"
	o->project_name = NULL;
#line 310 "bima-app-data.c"
#line 46 "appdata.gob"
	o->version = NULL;
#line 313 "bima-app-data.c"
#line 46 "appdata.gob"
	o->author = NULL;
#line 316 "bima-app-data.c"
#line 46 "appdata.gob"
	o->db_type = DB_POSTGRESQL;
#line 319 "bima-app-data.c"
#line 46 "appdata.gob"
	o->db_name = NULL;
#line 322 "bima-app-data.c"
#line 46 "appdata.gob"
	o->db_user_name = NULL;
#line 325 "bima-app-data.c"
#line 46 "appdata.gob"
	o->db_user_pass = NULL;
#line 328 "bima-app-data.c"
#line 46 "appdata.gob"
	o->num_modules = 1;
#line 331 "bima-app-data.c"
#line 46 "appdata.gob"
	o->modules = NULL;
#line 334 "bima-app-data.c"
#line 145 "appdata.gob"
	o->entities = NULL;
#line 337 "bima-app-data.c"
#line 158 "appdata.gob"
	o->relations = NULL;
#line 340 "bima-app-data.c"
#line 170 "appdata.gob"
	o->num_views = 1;
#line 343 "bima-app-data.c"
#line 170 "appdata.gob"
	o->views = NULL;
#line 346 "bima-app-data.c"
#line 182 "appdata.gob"
	o->reports = NULL;
#line 349 "bima-app-data.c"
#line 194 "appdata.gob"
	o->num_forms = 1;
#line 352 "bima-app-data.c"
#line 194 "appdata.gob"
	o->forms = NULL;
#line 355 "bima-app-data.c"
#line 206 "appdata.gob"
	o->template = NULL;
#line 358 "bima-app-data.c"
#line 222 "appdata.gob"
	o->query =  NULL ;
#line 361 "bima-app-data.c"
}
#undef __GOB_FUNCTION__
static void 
bima_app_data_class_init (BimaAppDataClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:App:Data::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("project_name" /* name */,
		 "prj name" /* nick */,
		 "name of project" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_PROJECT_NAME,
		param_spec);
	param_spec = g_param_spec_string
		("version" /* name */,
		 "version" /* nick */,
		 "version of project" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_VERSION,
		param_spec);
	param_spec = g_param_spec_string
		("author" /* name */,
		 "author" /* nick */,
		 "author of project" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_AUTHOR,
		param_spec);
	param_spec = g_param_spec_int
		("db_type" /* name */,
		 "db_type" /* nick */,
		 "db_type of project" /* blurb */,
		 G_MININT /* minimum */,
		 G_MAXINT /* maximum */,
		 0 /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DB_TYPE,
		param_spec);
	param_spec = g_param_spec_string
		("db_name" /* name */,
		 "db_name" /* nick */,
		 "db_name of project" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DB_NAME,
		param_spec);
	param_spec = g_param_spec_string
		("db_user_name" /* name */,
		 "db_user_name" /* nick */,
		 "db_user_name of project" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DB_USER_NAME,
		param_spec);
	param_spec = g_param_spec_string
		("db_user_pass" /* name */,
		 "db_user_pass" /* nick */,
		 "db_user_password of project" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DB_USER_PASS,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:App:Data::set_property"
{
	BimaAppData *self G_GNUC_UNUSED;

	self = BIMA_APP_DATA (object);

	switch (property_id) {
	case PROP_PROJECT_NAME:
		{
#line 77 "appdata.gob"
{ char *old = self->project_name; self->project_name = g_value_dup_string (VAL); g_free (old); }
#line 463 "bima-app-data.c"
		}
		break;
	case PROP_VERSION:
		{
#line 87 "appdata.gob"
{ char *old = self->version; self->version = g_value_dup_string (VAL); g_free (old); }
#line 470 "bima-app-data.c"
		}
		break;
	case PROP_AUTHOR:
		{
#line 97 "appdata.gob"
{ char *old = self->author; self->author = g_value_dup_string (VAL); g_free (old); }
#line 477 "bima-app-data.c"
		}
		break;
	case PROP_DB_TYPE:
		{
#line 106 "appdata.gob"
self->db_type = g_value_get_int (VAL);
#line 484 "bima-app-data.c"
		}
		break;
	case PROP_DB_NAME:
		{
#line 116 "appdata.gob"
{ char *old = self->db_name; self->db_name = g_value_dup_string (VAL); g_free (old); }
#line 491 "bima-app-data.c"
		}
		break;
	case PROP_DB_USER_NAME:
		{
#line 126 "appdata.gob"
{ char *old = self->db_user_name; self->db_user_name = g_value_dup_string (VAL); g_free (old); }
#line 498 "bima-app-data.c"
		}
		break;
	case PROP_DB_USER_PASS:
		{
#line 136 "appdata.gob"
{ char *old = self->db_user_pass; self->db_user_pass = g_value_dup_string (VAL); g_free (old); }
#line 505 "bima-app-data.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:App:Data::get_property"
{
	BimaAppData *self G_GNUC_UNUSED;

	self = BIMA_APP_DATA (object);

	switch (property_id) {
	case PROP_PROJECT_NAME:
		{
#line 77 "appdata.gob"
g_value_set_string (VAL, self->project_name);
#line 536 "bima-app-data.c"
		}
		break;
	case PROP_VERSION:
		{
#line 87 "appdata.gob"
g_value_set_string (VAL, self->version);
#line 543 "bima-app-data.c"
		}
		break;
	case PROP_AUTHOR:
		{
#line 97 "appdata.gob"
g_value_set_string (VAL, self->author);
#line 550 "bima-app-data.c"
		}
		break;
	case PROP_DB_TYPE:
		{
#line 106 "appdata.gob"
g_value_set_int (VAL, self->db_type);
#line 557 "bima-app-data.c"
		}
		break;
	case PROP_DB_NAME:
		{
#line 116 "appdata.gob"
g_value_set_string (VAL, self->db_name);
#line 564 "bima-app-data.c"
		}
		break;
	case PROP_DB_USER_NAME:
		{
#line 126 "appdata.gob"
g_value_set_string (VAL, self->db_user_name);
#line 571 "bima-app-data.c"
		}
		break;
	case PROP_DB_USER_PASS:
		{
#line 136 "appdata.gob"
g_value_set_string (VAL, self->db_user_pass);
#line 578 "bima-app-data.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 77 "appdata.gob"
gchar * 
bima_app_data_get_project_name (BimaAppData * self)
#line 598 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::get_project_name"
{
#line 77 "appdata.gob"
		gchar* val; g_object_get (G_OBJECT (self), "project_name", &val, NULL); return val;
}}
#line 605 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 77 "appdata.gob"
void 
bima_app_data_set_project_name (BimaAppData * self, gchar * val)
#line 611 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::set_project_name"
{
#line 77 "appdata.gob"
		g_object_set (G_OBJECT (self), "project_name", val, NULL);
}}
#line 618 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 87 "appdata.gob"
gchar * 
bima_app_data_get_version (BimaAppData * self)
#line 624 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::get_version"
{
#line 87 "appdata.gob"
		gchar* val; g_object_get (G_OBJECT (self), "version", &val, NULL); return val;
}}
#line 631 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 87 "appdata.gob"
void 
bima_app_data_set_version (BimaAppData * self, gchar * val)
#line 637 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::set_version"
{
#line 87 "appdata.gob"
		g_object_set (G_OBJECT (self), "version", val, NULL);
}}
#line 644 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 97 "appdata.gob"
gchar * 
bima_app_data_get_author (BimaAppData * self)
#line 650 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::get_author"
{
#line 97 "appdata.gob"
		gchar* val; g_object_get (G_OBJECT (self), "author", &val, NULL); return val;
}}
#line 657 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 97 "appdata.gob"
void 
bima_app_data_set_author (BimaAppData * self, gchar * val)
#line 663 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::set_author"
{
#line 97 "appdata.gob"
		g_object_set (G_OBJECT (self), "author", val, NULL);
}}
#line 670 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 106 "appdata.gob"
gint 
bima_app_data_get_db_type (BimaAppData * self)
#line 676 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::get_db_type"
{
#line 106 "appdata.gob"
		gint val; g_object_get (G_OBJECT (self), "db_type", &val, NULL); return val;
}}
#line 683 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 106 "appdata.gob"
void 
bima_app_data_set_db_type (BimaAppData * self, gint val)
#line 689 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::set_db_type"
{
#line 106 "appdata.gob"
		g_object_set (G_OBJECT (self), "db_type", val, NULL);
}}
#line 696 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 116 "appdata.gob"
gchar * 
bima_app_data_get_db_name (BimaAppData * self)
#line 702 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::get_db_name"
{
#line 116 "appdata.gob"
		gchar* val; g_object_get (G_OBJECT (self), "db_name", &val, NULL); return val;
}}
#line 709 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 116 "appdata.gob"
void 
bima_app_data_set_db_name (BimaAppData * self, gchar * val)
#line 715 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::set_db_name"
{
#line 116 "appdata.gob"
		g_object_set (G_OBJECT (self), "db_name", val, NULL);
}}
#line 722 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 126 "appdata.gob"
gchar * 
bima_app_data_get_db_user_name (BimaAppData * self)
#line 728 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::get_db_user_name"
{
#line 126 "appdata.gob"
		gchar* val; g_object_get (G_OBJECT (self), "db_user_name", &val, NULL); return val;
}}
#line 735 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 126 "appdata.gob"
void 
bima_app_data_set_db_user_name (BimaAppData * self, gchar * val)
#line 741 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::set_db_user_name"
{
#line 126 "appdata.gob"
		g_object_set (G_OBJECT (self), "db_user_name", val, NULL);
}}
#line 748 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 136 "appdata.gob"
gchar * 
bima_app_data_get_db_user_pass (BimaAppData * self)
#line 754 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::get_db_user_pass"
{
#line 136 "appdata.gob"
		gchar* val; g_object_get (G_OBJECT (self), "db_user_pass", &val, NULL); return val;
}}
#line 761 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 136 "appdata.gob"
void 
bima_app_data_set_db_user_pass (BimaAppData * self, gchar * val)
#line 767 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::set_db_user_pass"
{
#line 136 "appdata.gob"
		g_object_set (G_OBJECT (self), "db_user_pass", val, NULL);
}}
#line 774 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 228 "appdata.gob"
void 
bima_app_data_parse_file_diagram (BimaAppData * self, const gchar * file_name)
#line 780 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::parse_file_diagram"
#line 228 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 228 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 787 "bima-app-data.c"
{
#line 230 "appdata.gob"
	
		BimaModule *module = NULL;
		xmlDocPtr xml_doc;
		xmlNodePtr xml_node;

		xmlKeepBlanksDefault(0);

		xml_doc = xmlParseFile(file_name);
		if (xml_doc == NULL) 
			return ;

		xml_node = xmlDocGetRootElement(xml_doc);
		if (xml_node == NULL) 
			return ;
	
		if (self != NULL ) {
			g_object_unref((GObject *) self );
			//g_free(bgui->app_data);
			self = NULL;
		}
		self  = bima_app_data_new();

		if (!xmlStrcmp(xml_node->name, (const xmlChar *)"diagram")) {
			if (self->project_name)
				g_free(self->project_name);
		
			self->project_name = get_file_name_without_ext(file_name); 

			if (self->output_dir)
				g_free(self->output_dir);

			//set default module name as name of project
			module = bima_module_new();
			if (module != NULL ) {
				module->id = g_strdup(self->project_name);		
				module->name = g_strdup(self->project_name);
				module->parent_id = NULL;
				bima_app_data_add_module(self, module);
			}
			xmlFreeDoc(xml_doc);
			
			dia_er_parse (file_name,self);
			dia_er_parse_foreign_key(self); 
		} else if (!xmlStrcmp(xml_node->name, (const xmlChar *)"Bima")) {
			xmlFreeDoc(xml_doc);
			bma_file_parse (file_name,self);
		}	
		self->source_file = g_strdup(file_name);
		self->output_dir = g_strconcat(get_dir_name(file_name),"/","output",NULL);
	}}
#line 840 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 281 "appdata.gob"
void 
bima_app_data_add_module (BimaAppData * self, BimaModule * module)
#line 846 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::add_module"
#line 281 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 281 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 853 "bima-app-data.c"
{
#line 283 "appdata.gob"
	
		//g_printf(" add mdl %s prnt %s\n", module->id , module->parent_id);
		self->modules = g_list_append(self->modules, (gpointer) module);
	}}
#line 860 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 288 "appdata.gob"
void 
bima_app_data_delete_module (BimaAppData * self, gchar * id)
#line 866 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::delete_module"
#line 288 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 288 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 873 "bima-app-data.c"
{
#line 290 "appdata.gob"
	
		GList *list;
		list = bima_get_l_object_by_prop(self->modules , "id", id);
		if (list == NULL) 
			return;
		g_list_remove_link(self->modules , list);
		g_object_unref((GObject *) list->data); 
		g_list_free(list);
	}}
#line 885 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 300 "appdata.gob"
void 
bima_app_data_create_and_add_module (BimaAppData * self, gchar * id, gchar * parent_id)
#line 891 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::create_and_add_module"
#line 300 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 300 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 898 "bima-app-data.c"
{
#line 301 "appdata.gob"
	
		BimaModule *module = NULL;
		
		module = (BimaModule *) bima_get_object_by_prop(self->modules , "id", id);
		
		if (module) {
			return ;
		}
		
		module = bima_module_new();
		if (!module) {
			return;
		}
		
		module->id = g_strdup(id);
		module->name = g_strdup(id);
		module->parent_id = g_strdup(parent_id);
		
		bima_app_data_add_module(self,module);
	}}
#line 921 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 322 "appdata.gob"
void 
bima_app_data_add_entity (BimaAppData * self, BimaEntity * entity)
#line 927 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::add_entity"
#line 322 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 322 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 934 "bima-app-data.c"
{
#line 324 "appdata.gob"
	
		self->entities = g_list_append(self->entities, (gpointer) entity);
	}}
#line 940 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 328 "appdata.gob"
BimaEntity * 
bima_app_data_find_entity (BimaAppData * self, gchar * id)
#line 946 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::find_entity"
#line 328 "appdata.gob"
	g_return_val_if_fail (self != NULL, (BimaEntity * )0);
#line 328 "appdata.gob"
	g_return_val_if_fail (BIMA_IS_APP_DATA (self), (BimaEntity * )0);
#line 953 "bima-app-data.c"
{
#line 330 "appdata.gob"
	
		BimaEntity* obj;
		obj = (BimaEntity *)bima_get_object_by_prop(self->entities, "id",id);	
		return obj;
	}}
#line 961 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 336 "appdata.gob"
void 
bima_app_data_add_relation (BimaAppData * self, BimaRelation * relation)
#line 967 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::add_relation"
#line 336 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 336 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 974 "bima-app-data.c"
{
#line 338 "appdata.gob"
	
		self->relations = g_list_append(self->relations, (gpointer) relation);
	}}
#line 980 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 342 "appdata.gob"
BimaRelation * 
bima_app_data_find_relation (BimaAppData * self, gchar * id)
#line 986 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::find_relation"
#line 342 "appdata.gob"
	g_return_val_if_fail (self != NULL, (BimaRelation * )0);
#line 342 "appdata.gob"
	g_return_val_if_fail (BIMA_IS_APP_DATA (self), (BimaRelation * )0);
#line 993 "bima-app-data.c"
{
#line 344 "appdata.gob"
	
		BimaRelation* obj;
		obj = (BimaRelation *)bima_get_object_by_prop(self->relations, "id",id);	
		return obj;
	}}
#line 1001 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 350 "appdata.gob"
void 
bima_app_data_add_view (BimaAppData * self, BimaView * view)
#line 1007 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::add_view"
#line 350 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 350 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1014 "bima-app-data.c"
{
#line 352 "appdata.gob"
	
		self->views = g_list_append(self->views, (gpointer) view);
		self->num_views++;
	}}
#line 1021 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 357 "appdata.gob"
BimaView * 
bima_app_data_create_new_view (BimaAppData * self, gchar * entity_id)
#line 1027 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::create_new_view"
#line 357 "appdata.gob"
	g_return_val_if_fail (self != NULL, (BimaView * )0);
#line 357 "appdata.gob"
	g_return_val_if_fail (BIMA_IS_APP_DATA (self), (BimaView * )0);
#line 1034 "bima-app-data.c"
{
#line 359 "appdata.gob"
	
		BimaEntity *entity;
		BimaView *view = bima_view_new();
		
		entity = bima_get_object_by_prop(self->entities , "id", entity_id);
		if (entity == NULL) return NULL;
		
		view->id = g_strdup_printf("vw%d",self->num_views);
		view->primary_obj_id = g_strdup(entity_id);	
		view->name = g_strdup_printf("vw_%s_noname%d", g_ascii_strdown(entity->abbreviation,-1),self->num_views);
		view->title = g_strdup_printf("VIEW %s NONAME%d", g_ascii_strup(entity->abbreviation,-1), self->num_views);
				
		view->sql_text = g_strdup_printf("select * from %s ", entity->name);
		
		bima_app_data_add_view(self, view);
		return view;
	}}
#line 1054 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 377 "appdata.gob"
void 
bima_app_data_delete_view (BimaAppData * self, gchar * id)
#line 1060 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::delete_view"
#line 377 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 377 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1067 "bima-app-data.c"
{
#line 379 "appdata.gob"
	
		GList *llink;
		llink = bima_get_l_object_by_prop(self->views , "id", id);
		if (llink == NULL) 
			return;
		g_list_remove_link(self->views , llink);
		g_object_unref((GObject *) llink->data); 
		g_list_free(llink);
	}}
#line 1079 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 389 "appdata.gob"
void 
bima_app_data_add_report (BimaAppData * self, BimaForm * report)
#line 1085 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::add_report"
#line 389 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 389 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1092 "bima-app-data.c"
{
#line 391 "appdata.gob"
	
		self->reports = g_list_append(self->reports, (gpointer) report);
		self->num_forms++;
	}}
#line 1099 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 396 "appdata.gob"
BimaForm * 
bima_app_data_create_new_report (BimaAppData * self, gchar * entity_id, gchar * template_id)
#line 1105 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::create_new_report"
#line 396 "appdata.gob"
	g_return_val_if_fail (self != NULL, (BimaForm * )0);
#line 396 "appdata.gob"
	g_return_val_if_fail (BIMA_IS_APP_DATA (self), (BimaForm * )0);
#line 1112 "bima-app-data.c"
{
#line 398 "appdata.gob"
	
		BimaEntity *entity;
		BimaTemplateForm *tform;
		BimaForm *form = bima_form_new();
		
		tform = bima_get_object_by_prop(self->template->treports , "id", template_id);
		if (tform == NULL) return NULL;
		
		if (entity_id) {
			entity = bima_get_object_by_prop(self->entities , "id", entity_id);
			if (entity == NULL) return NULL;
		} else {
			entity = (BimaEntity *) (self->entities->data);
		}
		
		form->id = g_strdup_printf("%s%d",tform->prefix, self->num_forms);
		form->template_id = g_strdup(template_id);	
		if (entity) {
			form->primary_obj_id = g_strdup(entity->id);		
			form->name = g_strdup_printf("%s_%s_noname%d_%s", tform->prefix, g_ascii_strdown(entity->abbreviation,-1),self->num_forms, tform->suffix);
			form->title = g_strdup_printf("REPORT %s NONAME%d", g_ascii_strup(entity->abbreviation,-1), self->num_forms);				
			form->sql_text = g_strdup_printf("select * from %s ", entity->name);		
		} else {
			form->primary_obj_id = g_strdup(template_id);		
			form->name = g_strdup_printf("%s_noname%d_%s", tform->prefix, self->num_forms, tform->suffix);
			form->title = g_strdup_printf("REPORT NONAME%d", self->num_forms);				
			form->sql_text = g_strdup_printf("select * from NONAME ");				
		}
		
		bima_app_data_add_report(self, form);

		entity = NULL;	
		tform = NULL;	
		
		return form;
	}}
#line 1151 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 435 "appdata.gob"
void 
bima_app_data_delete_report (BimaAppData * self, gchar * id)
#line 1157 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::delete_report"
#line 435 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 435 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1164 "bima-app-data.c"
{
#line 437 "appdata.gob"
	
		GList *list;
		list = bima_get_l_object_by_prop(self->reports , "id", id);
		if (list == NULL) 
			return;
		g_list_remove_link(self->reports , list);
		g_object_unref((GObject *) list->data); 
		g_list_free(list);
	}}
#line 1176 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 447 "appdata.gob"
void 
bima_app_data_add_form (BimaAppData * self, BimaForm * form)
#line 1182 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::add_form"
#line 447 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 447 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1189 "bima-app-data.c"
{
#line 449 "appdata.gob"
	
		self->forms = g_list_append(self->forms, (gpointer) form);
		self->num_forms++;
	}}
#line 1196 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 454 "appdata.gob"
BimaForm * 
bima_app_data_create_new_form (BimaAppData * self, gchar * entity_id, gchar * template_id)
#line 1202 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::create_new_form"
#line 454 "appdata.gob"
	g_return_val_if_fail (self != NULL, (BimaForm * )0);
#line 454 "appdata.gob"
	g_return_val_if_fail (BIMA_IS_APP_DATA (self), (BimaForm * )0);
#line 1209 "bima-app-data.c"
{
#line 456 "appdata.gob"
	
		BimaEntity *entity;
		BimaTemplateForm *tform;
		BimaForm *form = bima_form_new();
		
		tform = bima_get_object_by_prop(self->template->tforms , "id", template_id);
		if (tform == NULL) return NULL;
		
		if (entity_id) {
			entity = bima_get_object_by_prop(self->entities , "id", entity_id);
			if (entity == NULL) return NULL;
		} else {
			entity = (BimaEntity *) (self->entities->data);
		}
		
		form->id = g_strdup_printf("%s%d",tform->prefix, self->num_forms);
		form->template_id = g_strdup(template_id);	
		if (entity) {
			form->primary_obj_id = g_strdup(entity->id);	
			form->name = g_strdup_printf("%s_%s_noname%d_%s",tform->prefix, g_ascii_strdown(entity->abbreviation,-1),self->num_forms,tform->suffix);
			form->title = g_strdup_printf("FORM %s NONAME%d", g_ascii_strup(entity->abbreviation,-1), self->num_forms);				
			form->sql_text = g_strdup_printf("select * from %s ", entity->name);		
		} else {
			form->primary_obj_id = g_strdup(template_id);	

			form->name = g_strdup_printf("%s_noname%d_%s", tform->prefix, self->num_forms, tform->suffix);
			form->title = g_strdup_printf("FORM NONAME%d", self->num_forms);				
			form->sql_text = g_strdup_printf("select * from NONAME ");				
		}

		bima_app_data_add_form(self, form);

		entity = NULL;	
		tform = NULL;	
		
		return form;
	}}
#line 1249 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 494 "appdata.gob"
void 
bima_app_data_delete_form (BimaAppData * self, gchar * id)
#line 1255 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::delete_form"
#line 494 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 494 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1262 "bima-app-data.c"
{
#line 496 "appdata.gob"
	
		GList *list;
		list = bima_get_l_object_by_prop(self->forms , "id", id);
		if (list == NULL) 
			return;
		g_list_remove_link(self->forms , list);
		g_object_unref((GObject *) list->data); 
		g_list_free(list);
	}}
#line 1274 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 506 "appdata.gob"
void 
bima_app_data_populate_views (BimaAppData * self)
#line 1280 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::populate_views"
#line 506 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 506 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1287 "bima-app-data.c"
{
#line 508 "appdata.gob"
	
		GList *l_tmp ,*l_tmp2,*l_tmp3,*l_tmp4;
		BimaEntity *entity ,*entity_pk;
		BimaForeignKey *fk,*fk2;
		BimaView *view = NULL;
		BimaAttribute *attr = NULL;
		BimaRelation *relation = NULL;
		gint n ;

		if (self->views)
			return;
			
		//parse one to one and one to many realtion		
		for (l_tmp=g_list_first(self->entities);l_tmp != NULL; l_tmp = l_tmp->next) {
			entity = (BimaEntity *) l_tmp->data;
			//g_printf("pop_v %s\n", entity->name);
			for (l_tmp2=g_list_first(entity->foreign_key);l_tmp2 != NULL; l_tmp2 = l_tmp2->next) {
				fk = (BimaForeignKey *)l_tmp2->data;
				entity_pk = bima_get_object_by_prop(self->entities , "id", fk->pk_obj_id);

				view = bima_view_new(); 
				g_return_if_fail(view!=NULL);
				view->primary_obj_id = g_strdup(entity->id);	
				if (fk->relation != NULL) {
					view->name = g_strdup_printf("vw_%s_%s", g_ascii_strdown(entity->abbreviation,-1), fk->relation->abbreviation,-1);
					view->title = g_strdup_printf("VIEW %s %s", g_ascii_strup(entity->abbreviation,-1), g_ascii_strup(fk->relation->abbreviation,-1));
				}
				else {
					view->name = g_strdup_printf("vw_%s_%s", g_ascii_strdown(entity->abbreviation,-1), g_ascii_strdown(entity_pk->abbreviation,-1));
					view->title = g_strdup_printf("VIEW %s %s", g_ascii_strup(entity->abbreviation,-1), g_ascii_strup(entity_pk->abbreviation,-1));
				}
				
				view->sql_text = g_strdup_printf("select * from %s a inner join %s b on ", entity->name, entity_pk->name);
				n = 0 ;
				for (l_tmp3=g_list_first(entity_pk->attributes);l_tmp3 != NULL; l_tmp3 = l_tmp3->next) {
					attr = (BimaAttribute *) l_tmp3->data ;
					if (attr->is_key) {
						if (n==0) {
							n = 1;
							view->sql_text = g_strconcat(view->sql_text ,g_strdup_printf("a.%s_%s = b.%s",fk->name , attr->name, attr->name), NULL);
						} else
							view->sql_text = g_strconcat(view->sql_text ,g_strdup_printf(" AND a.%s_%s = b.%s",  fk->name , attr->name ,attr->name), NULL);
					}
				}
				view->id = g_strdup_printf("vw%d",self->num_views);
				//g_print("%s %s\n %s\n",view->id,view->name,view->sql_text);
				bima_app_data_add_view(self, view);
			}
		}

		//parse many to many realtion
		for (l_tmp=g_list_first(self->relations);l_tmp != NULL; l_tmp = l_tmp->next) {
			relation = (BimaRelation *) l_tmp->data;
			for (l_tmp2=g_list_first(relation->foreign_key);l_tmp2 != NULL; l_tmp2 = l_tmp2->next) {
				fk = (BimaForeignKey *)l_tmp2->data;
				entity = bima_get_object_by_prop(self->entities , "id", fk->pk_obj_id);

				for (l_tmp3=g_list_first(relation->foreign_key);l_tmp3 != NULL; l_tmp3 = l_tmp3->next) {
					fk2 = (BimaForeignKey *)l_tmp3->data;
					if (!g_ascii_strcasecmp(fk->pk_obj_id, fk2->pk_obj_id)) {
						entity_pk = bima_get_object_by_prop(self->entities , "id", fk2->pk_obj_id);

						view = bima_view_new(); 
						g_return_if_fail(view!=NULL);
						view->primary_obj_id = g_strdup(entity->id);	

						view->name = g_strdup_printf("vw_%s_%s", g_ascii_strdown(entity->abbreviation,-1), g_ascii_strdown(entity_pk->abbreviation,-1));
						view->title = g_strdup_printf("VIEW %s %s", g_ascii_strup(entity->abbreviation,-1), g_ascii_strup(entity_pk->abbreviation,-1));
						view->sql_text = g_strdup_printf("select * from %s a , %s b , %s c where ", entity->name, relation->name, entity_pk->name);

						n = 0 ;
						for (l_tmp4=g_list_first(entity->attributes);l_tmp4 != NULL; l_tmp4 = l_tmp4->next) {
							attr = (BimaAttribute *) l_tmp4->data ;
							if (attr->is_key) {
								if (n==0) {
									n = 1;
									view->sql_text = g_strconcat(view->sql_text ,g_strdup_printf("b.%s_%s = a.%s",fk->name , attr->name, attr->name), NULL);
								} else
									view->sql_text = g_strconcat(view->sql_text ,g_strdup_printf(" AND b.%s_%s = a.%s",  fk->name , attr->name ,attr->name), NULL);
							}
						}

						for (l_tmp4=g_list_first(entity_pk->attributes);l_tmp4 != NULL; l_tmp4 = l_tmp4->next) {
							attr = (BimaAttribute *) l_tmp4->data ;
							if (attr->is_key) 
								view->sql_text = g_strconcat(view->sql_text ,g_strdup_printf(" AND b.%s_%s = c.%s",  fk->name , attr->name ,attr->name), NULL);
						}

						view->id = g_strdup_printf("vw%d",self->num_views);
						//g_print("%s %s\n %s\n",view->id,view->name,view->sql_text);
						bima_app_data_add_view(self, view);
					
					}
				}
			}
		}

	}}
#line 1388 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 607 "appdata.gob"
void 
bima_app_data_populate_forms (BimaAppData * self)
#line 1394 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::populate_forms"
#line 607 "appdata.gob"
	g_return_if_fail (self != NULL);
#line 607 "appdata.gob"
	g_return_if_fail (BIMA_IS_APP_DATA (self));
#line 1401 "bima-app-data.c"
{
#line 609 "appdata.gob"
	
		GList *l_tmp ,*l_tmp2,*l_tmp3,*l_tmp4, *tlist ;
		BimaEntity *entity ,*entity_pk;
		BimaForeignKey *fk,*fk2;
		//BimaReport *report;
		BimaForm *form = NULL;
		BimaAttribute *attr = NULL;
		BimaRelation *relation = NULL;
		BimaTemplateForm *tform = NULL;
		
		gint i,n ;

		if ((self->forms) || (self->reports))
			return ;
			
		for(i = 1; i <=2 ; i++ ) { 
			if (i == 1) {
				tlist = g_list_first(self->template->tforms);
			}
			else {
				tlist = g_list_first(self->template->treports);
			}
			for (;tlist != NULL; tlist = tlist->next) {
				
				tform = (BimaTemplateForm *) tlist->data;
				//g_printf("tform name %s reltype %d\n", tform->name, tform->relation_type);
				if ( (tform->relation_type == REL_NONE) || (tform->relation_type == REL_1TO1) ) {
					//parse without foreign key 
					for (l_tmp=g_list_first(self->entities);l_tmp != NULL; l_tmp = l_tmp->next) {
						entity = (BimaEntity *) l_tmp->data;
						//if (entity->foreign_key == NULL ) {
							form = bima_form_new(); 
							g_return_if_fail(form!=NULL);
							form->primary_obj_id = g_strdup(entity->id);	
							if (!g_ascii_strcasecmp("p_f_s", tform->file_format))  
								form->name = g_strdup_printf("%s_%s_%s", tform->prefix, g_ascii_strdown(entity->abbreviation,-1), tform->suffix); 
							else 
								form->name = g_strdup_printf("%s%s%s", tform->prefix, g_ascii_strdown(entity->abbreviation,-1), tform->suffix);
							form->title = g_strdup_printf("%s %s %s", g_ascii_strup(tform->prefix,-1), g_ascii_strup(entity->abbreviation,-1), g_ascii_strup(tform->suffix,-1));
							form->sql_text = g_strdup_printf("select * from %s %s ", entity->name , entity->name);
							form->template_id = g_strdup(tform->id);

							//form->id = g_strdup_printf("rpt%d",self->num_forms);
							form->id = g_strdup_printf("%s%d",tform->prefix, self->num_forms);
							//g_print("  NOREL %s %s\n %s\n",form->id,form->name,form->sql_text);
							if (i == 1)
								bima_app_data_add_form(self, form);
							else
								bima_app_data_add_report(self, form);

							if ( (form != NULL ) && (tform->properties != NULL) ) {
								bima_form_copy_properties(form, tform->properties );
								//g_printf("cp prop %d\n", g_list_length(form->properties));
							}								

						//}
					}
				} else if  ( (tform->relation_type == REL_1TOM) || (tform->relation_type == REL_MTO1)){	
					//parse one to many realtion	
					for (l_tmp=g_list_first(self->entities);l_tmp != NULL; l_tmp = l_tmp->next) {
						entity = (BimaEntity *) l_tmp->data;
						for (l_tmp2=g_list_first(entity->foreign_key);l_tmp2 != NULL; l_tmp2 = l_tmp2->next) {
							fk = (BimaForeignKey *)l_tmp2->data;
							//g_printf("rel type : \n");
							//g_printf("   %d\n",fk->relation->rel_type);
							//((fk->relation == NULL) && (tform->relation_type == REL_1TO1))
							//if ((fk->relation) && (tform->relation_type == fk->relation->rel_type) && (tform->relation_type == REL_1TOM)) {
							if ((tform->relation_type == fk->relation_type) && ((tform->relation_type == REL_1TOM) || (tform->relation_type == REL_MTO1))) {
								entity_pk = bima_get_object_by_prop(self->entities , "id", fk->pk_obj_id);
			
								form = bima_form_new(); 
								g_return_if_fail(form!=NULL);
								form->primary_obj_id = g_strdup(entity_pk->id);	
								//if (fk->relation) 
								//	form->name = g_strdup_printf("%s_%s_%s_%s",tform->prefix, g_ascii_strdown(entity_pk->abbreviation,-1), fk->relation->abbreviation, tform->suffix);
								//else
									form->name = g_strdup_printf("%s_%s_%s_%s",tform->prefix, g_ascii_strdown(entity_pk->abbreviation,-1), g_ascii_strdown(entity->abbreviation,-1), tform->suffix);
								
								form->title = g_strdup_printf("%s %s %s %s", g_ascii_strup(tform->prefix,-1), g_ascii_strup(entity_pk->abbreviation,-1), g_ascii_strup(entity->abbreviation,-1), g_ascii_strup(tform->suffix,-1));
								form->sql_text = g_strdup_printf("select * from %s %s inner join %s %s on ", entity_pk->name, fk->name, entity->name, entity->name);
								n = 0 ;
								for (l_tmp3=g_list_first(entity_pk->attributes);l_tmp3 != NULL; l_tmp3 = l_tmp3->next) {
									attr = (BimaAttribute *) l_tmp3->data ;
									if (attr->is_key) {
										if (n==0) {
											n = 1;
											form->sql_text = g_strconcat(form->sql_text ,g_strdup_printf("%s.%s_%s = %s.%s", entity->name, fk->name , attr->name, fk->name, attr->name), NULL);
										} else
											form->sql_text = g_strconcat(form->sql_text ,g_strdup_printf(" AND %s.%s_%s = %s.%s", entity->name, fk->name , attr->name, fk->name ,attr->name), NULL);
									}
								}
								form->template_id = g_strdup(tform->id);
								form->id = g_strdup_printf("%s%d",tform->prefix, self->num_forms);
								//g_print("  1TOM %s %s\n %s\n",form->id,form->name,form->sql_text);
								if (i == 1)
									bima_app_data_add_form(self, form);
								else
									bima_app_data_add_report(self, form);

								if ( (form != NULL ) && (tform->properties != NULL) ) {
									bima_form_copy_properties(form, tform->properties );
									//g_printf("cp prop %d\n", g_list_length(form->properties));
								}								

							}
						}
					}
				} else if (tform->relation_type == REL_MTOM) {
					//parse many to many realtion
					for (l_tmp=g_list_first(self->relations);l_tmp != NULL; l_tmp = l_tmp->next) {
						relation = (BimaRelation *) l_tmp->data;
						for (l_tmp2=g_list_first(relation->foreign_key);l_tmp2 != NULL; l_tmp2 = l_tmp2->next) {
							fk = (BimaForeignKey *)l_tmp2->data;
							entity = bima_get_object_by_prop(self->entities , "id", fk->pk_obj_id);
			
							for (l_tmp3=g_list_first(relation->foreign_key);l_tmp3 != NULL; l_tmp3 = l_tmp3->next) {
								fk2 = (BimaForeignKey *)l_tmp3->data;
								if (!g_ascii_strcasecmp(fk->pk_obj_id, fk2->pk_obj_id)) {
									entity_pk = bima_get_object_by_prop(self->entities , "id", fk2->pk_obj_id);
			
									form = bima_form_new(); 
									g_return_if_fail(form!=NULL);
									form->primary_obj_id = g_strdup(entity->id);	
			
									form->name = g_strdup_printf("%s_%s_%s_%s", tform->prefix, g_ascii_strdown(entity->abbreviation,-1), g_ascii_strdown(entity_pk->abbreviation,-1), tform->suffix);
									form->title = g_strdup_printf("%s %s %s", g_ascii_strup(tform->prefix,-1), g_ascii_strup(entity->abbreviation,-1), g_ascii_strup(entity_pk->abbreviation,-1));
									form->sql_text = g_strdup_printf("select * from %s a , %s b , %s c where ", entity->name, relation->name, entity_pk->name);
			
									n = 0 ;
									for (l_tmp4=g_list_first(entity->attributes);l_tmp4 != NULL; l_tmp4 = l_tmp4->next) {
										attr = (BimaAttribute *) l_tmp4->data ;
										if (attr->is_key) {
											if (n==0) {
												n = 1;
												form->sql_text = g_strconcat(form->sql_text ,g_strdup_printf("b.%s_%s = a.%s",fk->name , attr->name, attr->name), NULL);
											} else
												form->sql_text = g_strconcat(form->sql_text ,g_strdup_printf(" AND b.%s_%s = a.%s",  fk->name , attr->name ,attr->name), NULL);
										}
									}
			
									for (l_tmp4=g_list_first(entity_pk->attributes);l_tmp4 != NULL; l_tmp4 = l_tmp4->next) {
										attr = (BimaAttribute *) l_tmp4->data ;
										if (attr->is_key) 
											form->sql_text = g_strconcat(form->sql_text ,g_strdup_printf(" AND b.%s_%s = c.%s",  fk->name , attr->name ,attr->name), NULL);
									}
									form->template_id = g_strdup(tform->id);
									form->id = g_strdup_printf("%s%d",tform->prefix, self->num_forms);
									//g_print("  MTOM %s %s\n %s\n",form->id,form->name,form->sql_text);
									if (i == 1)
										bima_app_data_add_form(self, form);
									else
										bima_app_data_add_report(self, form);

									if ( (form != NULL ) && (tform->properties != NULL) ) {
										bima_form_copy_properties(form, tform->properties );
										//g_printf("cp prop %d\n", g_list_length(form->properties));
									}								
										
								}
							}
						}
					}
				}
			}
		}

	}}
#line 1571 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 777 "appdata.gob"
gint 
bima_app_data_write_to_xml (BimaAppData * self, gchar * file_name)
#line 1577 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::write_to_xml"
#line 777 "appdata.gob"
	g_return_val_if_fail (self != NULL, (gint )0);
#line 777 "appdata.gob"
	g_return_val_if_fail (BIMA_IS_APP_DATA (self), (gint )0);
#line 1584 "bima-app-data.c"
{
#line 779 "appdata.gob"
	
		GList *list;
		FILE *ofile;

		ofile = fopen(file_name , "w");
		if (!ofile) 
			return 1;
		
		fprintf(ofile, "<?xml version=\"1.0\"?>\n");
		fprintf(ofile, "<Bima Author=\"%s\">\n",self->author);

		fprintf(ofile, "  <Modules>\n");
		for (list=g_list_first(self->modules);list != NULL; list = list->next){
			if (list->data) 
				bima_module_write_to_xml ( (BimaModule *)(list->data), ofile);
		}
		fprintf(ofile, "  </Modules>\n");

		fprintf(ofile, "  <Entities>\n");
		for (list=g_list_first(self->entities);list != NULL; list = list->next){
			if (list->data) 
				bima_entity_write_to_xml ( (BimaEntity *)(list->data), ofile);
		}
		fprintf(ofile, "  </Entities>\n");

		fprintf(ofile, "  <Relations>\n");		
		for (list=g_list_first(self->relations);list != NULL; list = list->next){
			if (list->data) 
				bima_relation_write_to_xml ( (BimaRelation *)(list->data), ofile);
		}
		fprintf(ofile, "  </Relations>\n");
		
		fprintf(ofile, "\n</Bima>");

		fclose (ofile);
		return 0;
	}}
#line 1624 "bima-app-data.c"
#undef __GOB_FUNCTION__

#line 817 "appdata.gob"
BimaAppData * 
bima_app_data_new (void)
#line 1630 "bima-app-data.c"
{
#define __GOB_FUNCTION__ "Bima:App:Data::new"
{
#line 819 "appdata.gob"
	
		return GET_NEW;
	}}
#line 1638 "bima-app-data.c"
#undef __GOB_FUNCTION__
