/* Generated by GOB (v2.0.13)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include "bima-property.h"

#ifndef __BIMA_FORM_H__
#define __BIMA_FORM_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define BIMA_TYPE_FORM	(bima_form_get_type())
#define BIMA_FORM(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_form_get_type(), BimaForm)
#define BIMA_FORM_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), bima_form_get_type(), BimaForm const)
#define BIMA_FORM_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), bima_form_get_type(), BimaFormClass)
#define BIMA_IS_FORM(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), bima_form_get_type ())

#define BIMA_FORM_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), bima_form_get_type(), BimaFormClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BIMA_FORM__
#define __TYPEDEF_BIMA_FORM__
typedef struct _BimaForm BimaForm;
#endif
struct _BimaForm {
	GObject __parent__;
	/*< public >*/
	gchar * id;
	gchar * name;
	gchar * title;
	gchar * primary_obj_id;
	gchar * description;
	gchar * sql_text;
	gchar * template_id;
	gchar * module_id;
	GList * properties;
};

/*
 * Class definition
 */
typedef struct _BimaFormClass BimaFormClass;
struct _BimaFormClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	bima_form_get_type	(void);
gchar * 	bima_form_get_id	(BimaForm * self);
void 	bima_form_set_id	(BimaForm * self,
					gchar * val);
gchar * 	bima_form_get_name	(BimaForm * self);
void 	bima_form_set_name	(BimaForm * self,
					gchar * val);
gchar * 	bima_form_get_title	(BimaForm * self);
void 	bima_form_set_title	(BimaForm * self,
					gchar * val);
gchar * 	bima_form_get_primary_obj_id	(BimaForm * self);
void 	bima_form_set_primary_obj_id	(BimaForm * self,
					gchar * val);
gchar * 	bima_form_get_description	(BimaForm * self);
void 	bima_form_set_description	(BimaForm * self,
					gchar * val);
gchar * 	bima_form_get_sql_text	(BimaForm * self);
void 	bima_form_set_sql_text	(BimaForm * self,
					gchar * val);
void 	bima_form_copy_properties	(BimaForm * self,
					GList * properties);
BimaForm * 	bima_form_new	(void);

/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define BIMA_FORM_PROP_ID(arg)    	"id", __extension__ ({gchar *z = (arg); z;})
#define BIMA_FORM_GET_PROP_ID(arg)	"id", __extension__ ({gchar **z = (arg); z;})
#define BIMA_FORM_PROP_NAME(arg)    	"name", __extension__ ({gchar *z = (arg); z;})
#define BIMA_FORM_GET_PROP_NAME(arg)	"name", __extension__ ({gchar **z = (arg); z;})
#define BIMA_FORM_PROP_TITLE(arg)    	"title", __extension__ ({gchar *z = (arg); z;})
#define BIMA_FORM_GET_PROP_TITLE(arg)	"title", __extension__ ({gchar **z = (arg); z;})
#define BIMA_FORM_PROP_PRIMARY_OBJ_ID(arg)    	"primary_obj_id", __extension__ ({gchar *z = (arg); z;})
#define BIMA_FORM_GET_PROP_PRIMARY_OBJ_ID(arg)	"primary_obj_id", __extension__ ({gchar **z = (arg); z;})
#define BIMA_FORM_PROP_DESCRIPTION(arg)    	"description", __extension__ ({gchar *z = (arg); z;})
#define BIMA_FORM_GET_PROP_DESCRIPTION(arg)	"description", __extension__ ({gchar **z = (arg); z;})
#define BIMA_FORM_PROP_SQL_TEXT(arg)    	"sql_text", __extension__ ({gchar *z = (arg); z;})
#define BIMA_FORM_GET_PROP_SQL_TEXT(arg)	"sql_text", __extension__ ({gchar **z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define BIMA_FORM_PROP_ID(arg)    	"id",(gchar *)(arg)
#define BIMA_FORM_GET_PROP_ID(arg)	"id",(gchar **)(arg)
#define BIMA_FORM_PROP_NAME(arg)    	"name",(gchar *)(arg)
#define BIMA_FORM_GET_PROP_NAME(arg)	"name",(gchar **)(arg)
#define BIMA_FORM_PROP_TITLE(arg)    	"title",(gchar *)(arg)
#define BIMA_FORM_GET_PROP_TITLE(arg)	"title",(gchar **)(arg)
#define BIMA_FORM_PROP_PRIMARY_OBJ_ID(arg)    	"primary_obj_id",(gchar *)(arg)
#define BIMA_FORM_GET_PROP_PRIMARY_OBJ_ID(arg)	"primary_obj_id",(gchar **)(arg)
#define BIMA_FORM_PROP_DESCRIPTION(arg)    	"description",(gchar *)(arg)
#define BIMA_FORM_GET_PROP_DESCRIPTION(arg)	"description",(gchar **)(arg)
#define BIMA_FORM_PROP_SQL_TEXT(arg)    	"sql_text",(gchar *)(arg)
#define BIMA_FORM_GET_PROP_SQL_TEXT(arg)	"sql_text",(gchar **)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
