/* Generated by GOB (v2.0.13)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 13

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "bima-entity.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
/* self casting macros */
#define SELF(x) BIMA_ENTITY(x)
#define SELF_CONST(x) BIMA_ENTITY_CONST(x)
#define IS_SELF(x) BIMA_IS_ENTITY(x)
#define TYPE_SELF BIMA_TYPE_ENTITY
#define SELF_CLASS(x) BIMA_ENTITY_CLASS(x)

#define SELF_GET_CLASS(x) BIMA_ENTITY_GET_CLASS(x)

/* self typedefs */
typedef BimaEntity Self;
typedef BimaEntityClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void bima_entity_init (BimaEntity * o) G_GNUC_UNUSED;
static void bima_entity_class_init (BimaEntityClass * c) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_ID,
	PROP_NAME,
	PROP_ABBREVIATION,
	PROP_DESCRIPTION,
	PROP_MODULE_ID
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_id bima_entity_get_id
#define self_set_id bima_entity_set_id
#define self_get_name bima_entity_get_name
#define self_set_name bima_entity_set_name
#define self_get_abbreviation bima_entity_get_abbreviation
#define self_set_abbreviation bima_entity_set_abbreviation
#define self_get_description bima_entity_get_description
#define self_set_description bima_entity_set_description
#define self_get_module_id bima_entity_get_module_id
#define self_set_module_id bima_entity_set_module_id
#define self_add_attribute bima_entity_add_attribute
#define self_add_foreign_key bima_entity_add_foreign_key
#define self_add_foreign_attribute bima_entity_add_foreign_attribute
#define self_get_all_attribute bima_entity_get_all_attribute
#define self_get_nth_attribute bima_entity_get_nth_attribute
#define self_get_pk_string bima_entity_get_pk_string
#define self_write_to_xml bima_entity_write_to_xml
#define self_new bima_entity_new
GType
bima_entity_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (BimaEntityClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) bima_entity_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (BimaEntity),
			0 /* n_preallocs */,
			(GInstanceInitFunc) bima_entity_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "BimaEntity", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((BimaEntity *)g_object_new(bima_entity_get_type(), NULL))

extern BimaEntity *bima_app_data_find_entity();
extern BimaRelation *bima_app_data_find_relation();

/* a function for creating a new object of our type */
#include <stdarg.h>
static BimaEntity * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static BimaEntity *
GET_NEW_VARG (const char *first, ...)
{
	BimaEntity *ret;
	va_list ap;
	va_start (ap, first);
	ret = (BimaEntity *)g_object_new_valist (bima_entity_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Bima:Entity::finalize"
	BimaEntity *self G_GNUC_UNUSED = BIMA_ENTITY (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 50 "entity.gob"
	if(self->id) { g_free ((gpointer) self->id); self->id = NULL; }
#line 125 "bima-entity.c"
#line 59 "entity.gob"
	if(self->name) { g_free ((gpointer) self->name); self->name = NULL; }
#line 128 "bima-entity.c"
#line 68 "entity.gob"
	if(self->abbreviation) { g_free ((gpointer) self->abbreviation); self->abbreviation = NULL; }
#line 131 "bima-entity.c"
#line 77 "entity.gob"
	if(self->description) { g_free ((gpointer) self->description); self->description = NULL; }
#line 134 "bima-entity.c"
#line 87 "entity.gob"
	if(self->module_id) { g_free ((gpointer) self->module_id); self->module_id = NULL; }
#line 137 "bima-entity.c"
#define attributes (self->attributes)
#define VAR attributes
	{
#line 97 "entity.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 149 "bima-entity.c"
	memset(&attributes, 0, sizeof(attributes));
#undef VAR
#undef attributes
#define foreign_key (self->foreign_key)
#define VAR foreign_key
	{
#line 107 "entity.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 164 "bima-entity.c"
	memset(&foreign_key, 0, sizeof(foreign_key));
#undef VAR
#undef foreign_key
#define foreign_attr (self->foreign_attr)
#define VAR foreign_attr
	{
#line 117 "entity.gob"
	
			GList *list;
			for (list=g_list_first(VAR);list != NULL; list = list->next){
				if (list->data) 
					g_object_unref((GObject *) list->data); 
			}
		}
#line 179 "bima-entity.c"
	memset(&foreign_attr, 0, sizeof(foreign_attr));
#undef VAR
#undef foreign_attr
}
#undef __GOB_FUNCTION__

static void 
bima_entity_init (BimaEntity * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Entity::init"
#line 49 "entity.gob"
	o->id =  NULL ;
#line 192 "bima-entity.c"
#line 58 "entity.gob"
	o->name =  NULL ;
#line 195 "bima-entity.c"
#line 67 "entity.gob"
	o->abbreviation =  NULL ;
#line 198 "bima-entity.c"
#line 76 "entity.gob"
	o->description =  NULL ;
#line 201 "bima-entity.c"
#line 86 "entity.gob"
	o->module_id =  NULL ;
#line 204 "bima-entity.c"
#line 86 "entity.gob"
	o->attributes = NULL;
#line 207 "bima-entity.c"
#line 97 "entity.gob"
	o->num_of_attribute = 0;
#line 210 "bima-entity.c"
#line 97 "entity.gob"
	o->foreign_key = NULL;
#line 213 "bima-entity.c"
#line 107 "entity.gob"
	o->num_of_foreign_key = 0;
#line 216 "bima-entity.c"
#line 107 "entity.gob"
	o->foreign_attr = NULL;
#line 219 "bima-entity.c"
#line 117 "entity.gob"
	o->num_of_foreign_attribute = 0;
#line 222 "bima-entity.c"
#line 117 "entity.gob"
	o->is_weak = FALSE;
#line 225 "bima-entity.c"
#line 117 "entity.gob"
	o->num_of_key = 0;
#line 228 "bima-entity.c"
}
#undef __GOB_FUNCTION__
static void 
bima_entity_class_init (BimaEntityClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Bima:Entity::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("id" /* name */,
		 "id" /* nick */,
		 "id of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_ID,
		param_spec);
	param_spec = g_param_spec_string
		("name" /* name */,
		 "name" /* nick */,
		 "name of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_NAME,
		param_spec);
	param_spec = g_param_spec_string
		("abbreviation" /* name */,
		 "abbreviation" /* nick */,
		 "abbreviation of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_ABBREVIATION,
		param_spec);
	param_spec = g_param_spec_string
		("description" /* name */,
		 "description" /* nick */,
		 "description of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DESCRIPTION,
		param_spec);
	param_spec = g_param_spec_string
		("module_id" /* name */,
		 "module id" /* nick */,
		 "module of entity" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_MODULE_ID,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Entity::set_property"
{
	BimaEntity *self G_GNUC_UNUSED;

	self = BIMA_ENTITY (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 51 "entity.gob"
{ char *old = self->id; self->id = g_value_dup_string (VAL); g_free (old); }
#line 310 "bima-entity.c"
		}
		break;
	case PROP_NAME:
		{
#line 60 "entity.gob"
{ char *old = self->name; self->name = g_value_dup_string (VAL); g_free (old); }
#line 317 "bima-entity.c"
		}
		break;
	case PROP_ABBREVIATION:
		{
#line 69 "entity.gob"
{ char *old = self->abbreviation; self->abbreviation = g_value_dup_string (VAL); g_free (old); }
#line 324 "bima-entity.c"
		}
		break;
	case PROP_DESCRIPTION:
		{
#line 78 "entity.gob"
{ char *old = self->description; self->description = g_value_dup_string (VAL); g_free (old); }
#line 331 "bima-entity.c"
		}
		break;
	case PROP_MODULE_ID:
		{
#line 88 "entity.gob"
{ char *old = self->module_id; self->module_id = g_value_dup_string (VAL); g_free (old); }
#line 338 "bima-entity.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Bima:Entity::get_property"
{
	BimaEntity *self G_GNUC_UNUSED;

	self = BIMA_ENTITY (object);

	switch (property_id) {
	case PROP_ID:
		{
#line 51 "entity.gob"
g_value_set_string (VAL, self->id);
#line 369 "bima-entity.c"
		}
		break;
	case PROP_NAME:
		{
#line 60 "entity.gob"
g_value_set_string (VAL, self->name);
#line 376 "bima-entity.c"
		}
		break;
	case PROP_ABBREVIATION:
		{
#line 69 "entity.gob"
g_value_set_string (VAL, self->abbreviation);
#line 383 "bima-entity.c"
		}
		break;
	case PROP_DESCRIPTION:
		{
#line 78 "entity.gob"
g_value_set_string (VAL, self->description);
#line 390 "bima-entity.c"
		}
		break;
	case PROP_MODULE_ID:
		{
#line 88 "entity.gob"
g_value_set_string (VAL, self->module_id);
#line 397 "bima-entity.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 51 "entity.gob"
gchar * 
bima_entity_get_id (BimaEntity * self)
#line 417 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_id"
{
#line 51 "entity.gob"
		gchar* val; g_object_get (G_OBJECT (self), "id", &val, NULL); return val;
}}
#line 424 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 51 "entity.gob"
void 
bima_entity_set_id (BimaEntity * self, gchar * val)
#line 430 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::set_id"
{
#line 51 "entity.gob"
		g_object_set (G_OBJECT (self), "id", val, NULL);
}}
#line 437 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 60 "entity.gob"
gchar * 
bima_entity_get_name (BimaEntity * self)
#line 443 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_name"
{
#line 60 "entity.gob"
		gchar* val; g_object_get (G_OBJECT (self), "name", &val, NULL); return val;
}}
#line 450 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 60 "entity.gob"
void 
bima_entity_set_name (BimaEntity * self, gchar * val)
#line 456 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::set_name"
{
#line 60 "entity.gob"
		g_object_set (G_OBJECT (self), "name", val, NULL);
}}
#line 463 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 69 "entity.gob"
gchar * 
bima_entity_get_abbreviation (BimaEntity * self)
#line 469 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_abbreviation"
{
#line 69 "entity.gob"
		gchar* val; g_object_get (G_OBJECT (self), "abbreviation", &val, NULL); return val;
}}
#line 476 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 69 "entity.gob"
void 
bima_entity_set_abbreviation (BimaEntity * self, gchar * val)
#line 482 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::set_abbreviation"
{
#line 69 "entity.gob"
		g_object_set (G_OBJECT (self), "abbreviation", val, NULL);
}}
#line 489 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 78 "entity.gob"
gchar * 
bima_entity_get_description (BimaEntity * self)
#line 495 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_description"
{
#line 78 "entity.gob"
		gchar* val; g_object_get (G_OBJECT (self), "description", &val, NULL); return val;
}}
#line 502 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 78 "entity.gob"
void 
bima_entity_set_description (BimaEntity * self, gchar * val)
#line 508 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::set_description"
{
#line 78 "entity.gob"
		g_object_set (G_OBJECT (self), "description", val, NULL);
}}
#line 515 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 88 "entity.gob"
gchar * 
bima_entity_get_module_id (BimaEntity * self)
#line 521 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_module_id"
{
#line 88 "entity.gob"
		gchar* val; g_object_get (G_OBJECT (self), "module_id", &val, NULL); return val;
}}
#line 528 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 88 "entity.gob"
void 
bima_entity_set_module_id (BimaEntity * self, gchar * val)
#line 534 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::set_module_id"
{
#line 88 "entity.gob"
		g_object_set (G_OBJECT (self), "module_id", val, NULL);
}}
#line 541 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 130 "entity.gob"
void 
bima_entity_add_attribute (BimaEntity * self, BimaAttribute * attribute)
#line 547 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::add_attribute"
#line 130 "entity.gob"
	g_return_if_fail (self != NULL);
#line 130 "entity.gob"
	g_return_if_fail (BIMA_IS_ENTITY (self));
#line 554 "bima-entity.c"
{
#line 132 "entity.gob"
	
		if (attribute->is_key==TRUE) {
			self->attributes = g_list_prepend(self->attributes, (gpointer) attribute);
			self->num_of_key++;
		}else
			self->attributes = g_list_append(self->attributes, (gpointer) attribute);
		attribute->parent = (GObject *) self;
		self->num_of_attribute++;
	}}
#line 566 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 142 "entity.gob"
void 
bima_entity_add_foreign_key (BimaEntity * self, BimaForeignKey * fk)
#line 572 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::add_foreign_key"
#line 142 "entity.gob"
	g_return_if_fail (self != NULL);
#line 142 "entity.gob"
	g_return_if_fail (BIMA_IS_ENTITY (self));
#line 579 "bima-entity.c"
{
#line 144 "entity.gob"
	
		self->foreign_key = g_list_append(self->foreign_key, (gpointer) fk);
		self->num_of_foreign_key++;
	}}
#line 586 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 149 "entity.gob"
void 
bima_entity_add_foreign_attribute (BimaEntity * self, BimaForeignKey * fk)
#line 592 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::add_foreign_attribute"
#line 149 "entity.gob"
	g_return_if_fail (self != NULL);
#line 149 "entity.gob"
	g_return_if_fail (BIMA_IS_ENTITY (self));
#line 599 "bima-entity.c"
{
#line 151 "entity.gob"
	
		self->foreign_attr = g_list_append(self->foreign_attr, (gpointer) fk);
		// query need the real number of foreign attribute 
		if (fk->relation)
			self->num_of_foreign_attribute += bima_relation_get_num_of_attribute(fk->relation) ; //->num_of_attribute;
		//else
		//	self->num_of_foreign_attribute++;
	}}
#line 610 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 160 "entity.gob"
GList * 
bima_entity_get_all_attribute (BimaEntity * self, BimaAppData * app_data)
#line 616 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_all_attribute"
#line 160 "entity.gob"
	g_return_val_if_fail (self != NULL, (GList * )0);
#line 160 "entity.gob"
	g_return_val_if_fail (BIMA_IS_ENTITY (self), (GList * )0);
#line 623 "bima-entity.c"
{
#line 162 "entity.gob"
	
		BimaEntity *entity, *fk_entity;
		BimaAttribute *attribute, *cp_attribute;
		BimaForeignKey *fk;
		BimaRelation *relation;
		gchar *name=NULL;
		GList *rlist = NULL, *list1, *list;

		for (list= g_list_first(self->attributes);list != NULL; list = list->next){
			if (list->data) {
				attribute = bima_attribute_copy((BimaAttribute *)list->data);
				//attribute->attribute_type =  ATTRIBUTE;				
				rlist = g_list_append(rlist, (gpointer) attribute);				
			}
		}
	
		for (list1= g_list_first(self->foreign_key);list1 != NULL; list1 = list1->next){
			if (list1->data) 
				fk = (BimaForeignKey *)list1->data;
			else
				continue ;

			fk_entity = bima_app_data_find_entity(app_data,fk->pk_obj_id);
			for (list= g_list_first(fk_entity->attributes);list != NULL; list = list->next){
				if (list->data)
					attribute = bima_attribute_copy((BimaAttribute *)list->data);
				else
					continue;
					
				if (attribute->is_key == 1) {
					attribute->attribute_type =  ATTRIBUTE_FOREING_KEY;
					name = g_strdup_printf("%s_%s", fk->name,attribute->name);
					g_free(attribute->name);
					attribute->name = name;
					rlist = g_list_append(rlist, (gpointer) attribute);				
				}
			}
		}

		for (list1= g_list_first(self->foreign_attr);list1 != NULL; list1 = list1->next){
			if (list1->data) 
				fk = (BimaForeignKey *)list1->data;

			relation = bima_app_data_find_relation(app_data, fk->pk_obj_id);
			for (list= g_list_first(bima_relation_get_attributes(relation));list != NULL; list = list->next){
				if (list->data) {
					attribute = bima_attribute_copy((BimaAttribute *)list->data);
					attribute->attribute_type =  ATTRIBUTE_FOREING;
					name = g_strdup_printf("%s_%s", fk->name,attribute->name);
					g_free(attribute->name);
					attribute->name = name;
					rlist = g_list_append(rlist, (gpointer) attribute);				
				}
			}
		}
	
		return rlist;
	}}
#line 680 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 219 "entity.gob"
GObject * 
bima_entity_get_nth_attribute (BimaEntity * self, gint n)
#line 686 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_nth_attribute"
#line 219 "entity.gob"
	g_return_val_if_fail (self != NULL, (GObject * )0);
#line 219 "entity.gob"
	g_return_val_if_fail (BIMA_IS_ENTITY (self), (GObject * )0);
#line 693 "bima-entity.c"
{
#line 221 "entity.gob"
	
		GList *list=NULL, *list1 = NULL;
		BimaForeignKey *fk;		

		gint i;
		i=0;
		for (list=g_list_first(self->attributes);list != NULL; list = list->next){
			//g_printf("Ent %d of %d \n", i, n);
			if (i==n)
				return (GObject *) (list->data);
			i++;			
		}
		for (list=g_list_first(self->foreign_key);list != NULL; list = list->next){
			//g_printf("Ent %d of %d \n", i, n);
			if (i==n)
				return (GObject *) (list->data);
			i++;			
		}

		for (list=g_list_first(self->foreign_attr);list != NULL; list = list->next){
			if (list->data) {
				fk = (BimaForeignKey *) list->data;
				for (list1=g_list_first(bima_relation_get_attributes(fk->relation));list1 != NULL; list1 = list1->next){
					if (i==n)
						return (GObject *) (list1->data);
					i++;							
				}
			}
		}
		
		return NULL;
	}}
#line 728 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 254 "entity.gob"
gchar * 
bima_entity_get_pk_string (BimaEntity * self, gchar * separator, gchar * alias)
#line 734 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::get_pk_string"
#line 254 "entity.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 254 "entity.gob"
	g_return_val_if_fail (BIMA_IS_ENTITY (self), (gchar * )0);
#line 741 "bima-entity.c"
{
#line 256 "entity.gob"
	
		gchar *str_tmp=NULL;
		BimaAttribute *attribute;
		GList *list;
	
		if (self) {			
			for (list=g_list_first(self->attributes);list != NULL; list = list->next){			
				if (list->data) { 
					attribute = (BimaAttribute *) list->data;
					if ( attribute->is_key == 1 ) {
						if (!str_tmp)
							str_tmp = g_strdup_printf("%s.%s",alias,attribute->name);
						else 
							str_tmp = g_strconcat( str_tmp , separator,  g_strdup_printf("%s.%s",alias,attribute->name),NULL);
					}
				}
			}
		}
		return str_tmp;	
	}}
#line 764 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 277 "entity.gob"
void 
bima_entity_write_to_xml (BimaEntity * self, FILE * ofile)
#line 770 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::write_to_xml"
#line 277 "entity.gob"
	g_return_if_fail (self != NULL);
#line 277 "entity.gob"
	g_return_if_fail (BIMA_IS_ENTITY (self));
#line 777 "bima-entity.c"
{
#line 279 "entity.gob"
	
		GList *list;

		fprintf(ofile, "\t<Entity id=\"%s\" name=\"%s\" module=\"%s\" is_weak=\"%d\" num_of_key=\"%d\" abbreviation=\"%s\">\n", \ 
			self->id , self->name, self->module_id, self->is_weak, self->num_of_key, self->abbreviation);

		if (self->description)
			fprintf(ofile, "\t\t<Description>%s</Description>\n", self->description);
		
		fprintf(ofile, "\t\t<Attributes>\n");
		for (list=g_list_first(self->attributes);list != NULL; list = list->next){
			if (list->data) 
				bima_attribute_write_to_xml((BimaAttribute *) list->data, ofile);			
		}
		fprintf(ofile, "\t\t</Attributes>\n");

		if (self->foreign_key) {
			fprintf(ofile, "\t\t<ForeignKeys>\n");
			for (list=g_list_first(self->foreign_key);list != NULL; list = list->next){
				if (list->data) 
					bima_foreign_key_write_to_xml((BimaForeignKey *) list->data, ofile);			
			}
			fprintf(ofile, "\t\t</ForeignKeys>\n");
		}
		
		if (self->foreign_attr) {
			fprintf(ofile, "\t\t<ForeignAttributes>\n");
			for (list=g_list_first(self->foreign_attr);list != NULL; list = list->next){
				if (list->data) 
					bima_foreign_key_write_to_xml((BimaForeignKey *) list->data, ofile);			
			}
			fprintf(ofile, "\t\t</ForeignAttributes>\n");
		}
		fprintf(ofile, "\t</Entity>\n");
	}}
#line 815 "bima-entity.c"
#undef __GOB_FUNCTION__

#line 315 "entity.gob"
BimaEntity * 
bima_entity_new (void)
#line 821 "bima-entity.c"
{
#define __GOB_FUNCTION__ "Bima:Entity::new"
{
#line 317 "entity.gob"
	
		return GET_NEW;
	}}
#line 829 "bima-entity.c"
#undef __GOB_FUNCTION__
